services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pharos-graphql-server
    working_dir: /usr/src/app
    restart: always
    environment:
      REDISHOST: redis
    ports:
      - "4444:4444"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
