drop table if exists `ncats_idg_list`;
drop table if exists `ncats_idg_list_type`;

CREATE TABLE `ncats_idg_list_type`
(
    `id`        int         NOT NULL AUTO_INCREMENT,
    `list_type` varchar(45) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `list_type_UNIQUE` (`list_type`)
) DEFAULT CHARSET = utf8;

CREATE TABLE `ncats_idg_list`
(
    `id`         int         NOT NULL AUTO_INCREMENT,
    `protein_id` int         NOT NULL,
    `symbol`     varchar(20) NOT NULL,
    `family`     varchar(20) NOT NULL,
    `idg_list`   int         NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `list_type` FOREIGN KEY (`idg_list`) REFERENCES `ncats_idg_list_type` (`id`),
    CONSTRAINT `protein` FOREIGN KEY (`protein_id`) REFERENCES `protein` (`id`)
) DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS _TEMP;
CREATE TABLE `_TEMP` (
    `symbol` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
    `family` varchar(20) DEFAULT NULL,
    `notes` varchar(256) DEFAULT NULL
) DEFAULT CHARSET=utf8;

# import data for year 1 IDG targets
INSERT INTO _TEMP VALUES
('ADGRA1', 'GPCR', null),
('ADGRA2', 'GPCR', null),
('ADGRA3', 'GPCR', null),
('ADGRB1', 'GPCR', null),
('ADGRB2', 'GPCR', null),
('ADGRB3', 'GPCR', null),
('ADGRD1', 'GPCR', null),
('ADGRD2', 'GPCR', null),
('ADGRE1', 'GPCR', null),
('ADGRE2', 'GPCR', null),
('ADGRE3', 'GPCR', null),
('ADGRE5', 'GPCR', 'Changed symbol from ADGRE5. Current symbol in HGNC is ADGRE5 but UniProt still has CD97. Changed back during pharos import to match current data'),
('ADGRF1', 'GPCR', null),
('ADGRF2', 'GPCR', null),
('ADGRF3', 'GPCR', null),
('ADGRF4', 'GPCR', null),
('ADGRF5', 'GPCR', null),
('ADGRG2', 'GPCR', null),
('ADGRG3', 'GPCR', null),
('ADGRG4', 'GPCR', null),
('ADGRG5', 'GPCR', null),
('ADGRG6', 'GPCR', null),
('ADGRG7', 'GPCR', null),
('ADGRL4', 'GPCR', null),
('CHRM5', 'GPCR', null),
('FZD10', 'GPCR', null),
('GNRHR2', 'GPCR', null),
('GPR101', 'GPCR', null),
('GPR12', 'GPCR', null),
('GPR132', 'GPCR', null),
('GPR135', 'GPCR', null),
('GPR137', 'GPCR', null),
('GPR139', 'GPCR', null),
('GPR141', 'GPCR', null),
('GPR142', 'GPCR', null),
('GPR143', 'GPCR', null),
('GPR146', 'GPCR', null),
('GPR148', 'GPCR', null),
('GPR149', 'GPCR', null),
('GPR15', 'GPCR', null),
('GPR150', 'GPCR', null),
('GPR151', 'GPCR', null),
('GPR152', 'GPCR', null),
('GPR153', 'GPCR', null),
('GPR156', 'GPCR', null),
('GPR157', 'GPCR', null),
('GPR160', 'GPCR', null),
('GPR161', 'GPCR', null),
('GPR162', 'GPCR', null),
('GPR17', 'GPCR', null),
('GPR171', 'GPCR', null),
('GPR173', 'GPCR', null),
('GPR174', 'GPCR', null),
('GPR18', 'GPCR', null),
('GPR182', 'GPCR', null),
('GPR183', 'GPCR', null),
('GPR19', 'GPCR', null),
('GPR20', 'GPCR', null),
('GPR21', 'GPCR', null),
('GPR22', 'GPCR', null),
('GPR25', 'GPCR', null),
('GPR26', 'GPCR', null),
('GPR27', 'GPCR', null),
('GPR3', 'GPCR', null),
('GPR31', 'GPCR', null),
('GPR32', 'GPCR', null),
('GPR32P1', 'GPCR', null),
('GPR34', 'GPCR', null),
('GPR35', 'GPCR', null),
('GPR37', 'GPCR', null),
('GPR37L1', 'GPCR', null),
('GPR39', 'GPCR', null),
('GPR4', 'GPCR', null),
('GPR45', 'GPCR', null),
('GPR50', 'GPCR', null),
('GPR52', 'GPCR', null),
('GPR55', 'GPCR', null),
('GPR6', 'GPCR', null),
('GPR61', 'GPCR', null),
('GPR62', 'GPCR', null),
('GPR63', 'GPCR', null),
('GPR65', 'GPCR', null),
('GPR68', 'GPCR', null),
('GPR75', 'GPCR', null),
('GPR78', 'GPCR', null),
('GPR82', 'GPCR', null),
('GPR83', 'GPCR', null),
('GPR84', 'GPCR', null),
('GPR85', 'GPCR', null),
('GPR87', 'GPCR', null),
('GPR88', 'GPCR', null),
('GPRC5A', 'GPCR', null),
('GPRC5B', 'GPCR', null),
('GPRC5C', 'GPCR', null),
('GPRC5D', 'GPCR', null),
('HCAR1', 'GPCR', null),
('HCAR3', 'GPCR', null),
('HTR1E', 'GPCR', null),
('HTR5A', 'GPCR', null),
('LPAR6', 'GPCR', null),
('MAS1', 'GPCR', null),
('MAS1L', 'GPCR', null),
('MRGPRE', 'GPCR', null),
('MRGPRF', 'GPCR', null),
('MRGPRG', 'GPCR', null),
('MRGPRX1', 'GPCR', null),
('MRGPRX2', 'GPCR', null),
('MRGPRX3', 'GPCR', null),
('MRGPRX4', 'GPCR', null),
('MTNR1A', 'GPCR', null),
('MTNR1B', 'GPCR', null),
('NPBWR1', 'GPCR', null),
('NPBWR2', 'GPCR', null),
('NPY2R', 'GPCR', null),
('NPY5R', 'GPCR', null),
('OXER1', 'GPCR', null),
('OXGR1', 'GPCR', null),
('P2RY10', 'GPCR', null),
('P2RY11', 'GPCR', null),
('PROKR1', 'GPCR', null),
('QRFPR', 'GPCR', null),
('RXFP3', 'GPCR', null),
('RXFP4', 'GPCR', null),
('SUCNR1', 'GPCR', null),
('TAAR2', 'GPCR', null),
('TAAR3P', 'GPCR', 'Changed symbol from TAAR3. Current symbol in HGNC is TAAR3 but UniProt still has TAAR3P.'),
('TAAR8', 'GPCR', null),
('TAAR9', 'GPCR', null),
('TAS2R1', 'GPCR', null),
('TAS2R10', 'GPCR', null),
('TAS2R13', 'GPCR', null),
('TAS2R14', 'GPCR', null),
('TAS2R16', 'GPCR', null),
('TAS2R19', 'GPCR', null),
('TAS2R20', 'GPCR', null),
('TAS2R3', 'GPCR', null),
('TAS2R30', 'GPCR', null),
('TAS2R31', 'GPCR', null),
('TAS2R39', 'GPCR', null),
('TAS2R4', 'GPCR', null),
('TAS2R40', 'GPCR', null),
('TAS2R41', 'GPCR', null),
('TAS2R42', 'GPCR', null),
('TAS2R43', 'GPCR', null),
('TAS2R46', 'GPCR', null),
('TAS2R5', 'GPCR', null),
('TAS2R50', 'GPCR', null),
('TAS2R60', 'GPCR', null),
('TAS2R7', 'GPCR', null),
('TAS2R8', 'GPCR', null),
('TAS2R9', 'GPCR', null),
('TPRA1', 'GPCR', null),
('ASIC4', 'Ion channel', null),
('BEST4', 'Ion channel', null),
('CACNA2D2', 'Ion channel', null),
('CACNA2D3', 'Ion channel', null),
('CACNA2D4', 'Ion channel', null),
('CACNB1', 'Ion channel', null),
('CACNB2', 'Ion channel', null),
('CACNB3', 'Ion channel', null),
('CACNB4', 'Ion channel', null),
('CACNG1', 'Ion channel', null),
('CACNG3', 'Ion channel', null),
('CACNG4', 'Ion channel', null),
('CACNG5', 'Ion channel', null),
('CACNG6', 'Ion channel', null),
('CACNG7', 'Ion channel', null),
('CACNG8', 'Ion channel', null),
('CATSPER2', 'Ion channel', null),
('CHRNA10', 'Ion channel', null),
('CHRNA2', 'Ion channel', null),
('CHRNB1', 'Ion channel', null),
('CHRND', 'Ion channel', null),
('CLCA2', 'Ion channel', null),
('CLCA4', 'Ion channel', null),
('CLCC1', 'Ion channel', null),
('CLCN6', 'Ion channel', null),
('CLCNKA', 'Ion channel', null),
('CLIC2', 'Ion channel', null),
('CLIC3', 'Ion channel', null),
('CLIC5', 'Ion channel', null),
('CLIC6', 'Ion channel', null),
('CNGA4', 'Ion channel', null),
('CALHM4', 'Ion channel', 'Changed symbol from FAM26D. CALHM4 is the current symbol according to HGNC.'),
('CALHM5', 'Ion channel', 'Changed symbol from FAM26E. CALHM5 is the current symbol according to HGNC.'),
('CALHM6', 'Ion channel', 'Changed symbol from FAM26F. CALHM6 is the current symbol according to HGNC.'),
('FXYD3', 'Ion channel', null),
('FXYD7', 'Ion channel', null),
('GABRA5', 'Ion channel', null),
('GABRG1', 'Ion channel', null),
('GABRP', 'Ion channel', null),
('GABRR1', 'Ion channel', null),
('GLRA3', 'Ion channel', null),
('GLRA4', 'Ion channel', null),
('GLRB', 'Ion channel', null),
('GPR89A', 'Ion channel', null),
('GPR89B', 'Ion channel', null),
('GRID1', 'Ion channel', null),
('GRIK3', 'Ion channel', null),
('HTR3C', 'Ion channel', null),
('HTR3D', 'Ion channel', null),
('HTR3E', 'Ion channel', null),
('KCNA6', 'Ion channel', null),
('KCNA7', 'Ion channel', null),
('KCNAB2', 'Ion channel', null),
('KCNAB3', 'Ion channel', null),
('KCNC4', 'Ion channel', null),
('KCND1', 'Ion channel', null),
('KCNG2', 'Ion channel', null),
('KCNG3', 'Ion channel', null),
('KCNG4', 'Ion channel', null),
('KCNH4', 'Ion channel', null),
('KCNH6', 'Ion channel', null),
('KCNH8', 'Ion channel', null),
('KCNIP1', 'Ion channel', null),
('KCNIP4', 'Ion channel', null),
('KCNJ14', 'Ion channel', null),
('KCNJ15', 'Ion channel', null),
('KCNJ18', 'Ion channel', null),
('KCNK12', 'Ion channel', null),
('KCNK4', 'Ion channel', null),
('KCNK7', 'Ion channel', null),
('KCNMB3', 'Ion channel', null),
('KCNMB4', 'Ion channel', null),
('KCNN1', 'Ion channel', null),
('KCNS1', 'Ion channel', null),
('KCNS2', 'Ion channel', null),
('KCNS3', 'Ion channel', null),
('KCNT1', 'Ion channel', null),
('KCNT2', 'Ion channel', null),
('KCNV1', 'Ion channel', null),
('LRRC38', 'Ion channel', null),
('LRRC55', 'Ion channel', null),
('PANX2', 'Ion channel', null),
('PKD1L2', 'Ion channel', null),
('PKD1L3', 'Ion channel', null),
('PKD2L2', 'Ion channel', null),
('PLLP', 'Ion channel', null),
('SCN2B', 'Ion channel', null),
('SCN3B', 'Ion channel', null),
('SCN7A', 'Ion channel', null),
('SCNN1B', 'Ion channel', null),
('SCNN1D', 'Ion channel', null),
('SLC26A1', 'Ion channel', null),
('TMC3', 'Ion channel', null),
('TMC4', 'Ion channel', null),
('TMC5', 'Ion channel', null),
('TMC7', 'Ion channel', null),
('TMEM38B', 'Ion channel', null),
('TMEM63A', 'Ion channel', null),
('TMEM63B', 'Ion channel', null),
('TMEM63C', 'Ion channel', null),
('TTYH1', 'Ion channel', null),
('TTYH2', 'Ion channel', null),
('ADCK1', 'Kinase', null),
('BRSK1', 'Kinase', null),
('BRSK2', 'Kinase', null),
('CAMKK2', 'Kinase', null),
('CDC42BPA', 'Kinase', null),
('CDK11A', 'Kinase', null),
('CDK12', 'Kinase', null),
('CDK13', 'Kinase', null),
('CDK16', 'Kinase', null),
('CDK19', 'Kinase', null),
('CDK20', 'Kinase', null),
('CDKL5', 'Kinase', null),
('COQ8A', 'Kinase', null),
('CSNK1A1L', 'Kinase', null),
('CSNK2A3', 'Kinase', null),
('DCLK3', 'Kinase', null),
('DSTYK', 'Kinase', null),
('HIPK1', 'Kinase', null),
('HIPK3', 'Kinase', null),
('ICK', 'Kinase', null),
('LMTK2', 'Kinase', null),
('MAP3K15', 'Kinase', null),
('MAP3K21', 'Kinase', null),
('MARK1', 'Kinase', null),
('MARK3', 'Kinase', null),
('MKNK1', 'Kinase', null),
('NEK1', 'Kinase', null),
('NEK3', 'Kinase', null),
('NEK8', 'Kinase', null),
('NEK9', 'Kinase', null),
('NUAK2', 'Kinase', null),
('OBSCN', 'Kinase', null),
('PAN3', 'Kinase', null),
('PIP5K1C', 'Kinase', null),
('RIOK2', 'Kinase', null),
('RNASEL', 'Kinase', null),
('SBK1', 'Kinase', null),
('STK17B', 'Kinase', null),
('STK19', 'Kinase', null),
('TAOK1', 'Kinase', null),
('TAOK2', 'Kinase', null),
('TSSK2', 'Kinase', null),
('VRK3', 'Kinase', null),
('WNK3', 'Kinase', null),
('ADCK2', 'Kinase', null),
('ADCK5', 'Kinase', null),
('ALPK2', 'Kinase', null),
('ALPK3', 'Kinase', null),
('BCKDK', 'Kinase', null),
('CAMK1D', 'Kinase', null),
('CAMK1G', 'Kinase', null),
('CAMKK1', 'Kinase', null),
('CAMKV', 'Kinase', null),
('CDC42BPB', 'Kinase', null),
('CDC42BPG', 'Kinase', null),
('CDK10', 'Kinase', null),
('CDK11B', 'Kinase', null),
('CDK14', 'Kinase', null),
('CDK15', 'Kinase', null),
('CDK17', 'Kinase', null),
('CDK18', 'Kinase', null),
('CDKL1', 'Kinase', null),
('CDKL2', 'Kinase', null),
('CDKL3', 'Kinase', null),
('CDKL4', 'Kinase', null),
('CLK3', 'Kinase', null),
('CLK4', 'Kinase', null),
('COQ8B', 'Kinase', null),
('CSNK1G1', 'Kinase', null),
('CSNK1G2', 'Kinase', null),
('CSNK1G3', 'Kinase', null),
('CSNK2A2', 'Kinase', null),
('DYRK1B', 'Kinase', null),
('DYRK2', 'Kinase', null),
('DYRK3', 'Kinase', null),
('DYRK4', 'Kinase', null),
('EEF2K', 'Kinase', null),
('ERN2', 'Kinase', null),
('HIPK4', 'Kinase', null),
('LMTK3', 'Kinase', null),
('LRRK1', 'Kinase', null),
('LTK', 'Kinase', null),
('MAP3K10', 'Kinase', null),
('MAP3K14', 'Kinase', null),
('MAPK15', 'Kinase', null),
('MAPK4', 'Kinase', null),
('MARK4', 'Kinase', null),
('MAST2', 'Kinase', null),
('MAST3', 'Kinase', null),
('MAST4', 'Kinase', null),
('MKNK2', 'Kinase', null),
('NEK10', 'Kinase', null),
('NEK11', 'Kinase', null),
('NEK4', 'Kinase', null),
('NEK5', 'Kinase', null),
('NEK6', 'Kinase', null),
('NEK7', 'Kinase', null),
('NIM1K', 'Kinase', null),
('NRBP2', 'Kinase', null),
('NRK', 'Kinase', null),
('PAK3', 'Kinase', null),
('PAK5', 'Kinase', null),
('PAK6', 'Kinase', null),
('PDIK1L', 'Kinase', null),
('PHKG1', 'Kinase', null),
('PHKG2', 'Kinase', null),
('PI4KA', 'Kinase', null),
('PIK3C2B', 'Kinase', null),
('PIK3C2G', 'Kinase', null),
('PIP4K2C', 'Kinase', null),
('PIP5K1A', 'Kinase', null),
('PIP5K1B', 'Kinase', null),
('PKMYT1', 'Kinase', null),
('PKN3', 'Kinase', null),
('PNCK', 'Kinase', null),
('POMK', 'Kinase', null),
('PRAG1', 'Kinase', null),
('PRKACB', 'Kinase', null),
('PRKACG', 'Kinase', null),
('PRKCQ', 'Kinase', null),
('PRPF4B', 'Kinase', null),
('PSKH1', 'Kinase', null),
('PSKH2', 'Kinase', null),
('PXK', 'Kinase', null),
('RIOK1', 'Kinase', null),
('RIOK3', 'Kinase', null),
('RPS6KC1', 'Kinase', null),
('RPS6KL1', 'Kinase', null),
('SBK2', 'Kinase', null),
('SBK3', 'Kinase', null),
('SCYL1', 'Kinase', null),
('SCYL2', 'Kinase', null),
('SCYL3', 'Kinase', null),
('SGK494', 'Kinase', null),
('SRPK3', 'Kinase', null),
('STK17A', 'Kinase', null),
('STK3', 'Kinase', null),
('STK31', 'Kinase', null),
('STK32A', 'Kinase', null),
('STK32B', 'Kinase', null),
('STK32C', 'Kinase', null),
('STK33', 'Kinase', null),
('STK36', 'Kinase', null),
('STK38L', 'Kinase', null),
('STK40', 'Kinase', null),
('STKLD1', 'Kinase', null),
('TBCK', 'Kinase', null),
('TESK1', 'Kinase', null),
('TESK2', 'Kinase', null),
('TLK1', 'Kinase', null),
('TLK2', 'Kinase', null),
('TP53RK', 'Kinase', null),
('TSSK1B', 'Kinase', null),
('TSSK3', 'Kinase', null),
('TSSK4', 'Kinase', null),
('TSSK6', 'Kinase', null),
('TTBK1', 'Kinase', null),
('TTBK2', 'Kinase', null),
('ULK4', 'Kinase', null),
('VRK2', 'Kinase', null),
('WEE2', 'Kinase', null),
('WNK2', 'Kinase', null);

# update list type table
Insert into ncats_idg_list_type values
(1,'Year 1');

# update list table
Insert into ncats_idg_list
select
    null as id,
    (Select id from protein where sym = _TEMP.symbol) as protein_id,
    _TEMP.symbol as symbol,
    _TEMP.family as family,
    1 as idg_list
from _TEMP;

Drop table _TEMP;

CREATE TABLE `_TEMP` (
                         `symbol` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
                         `family` varchar(20) DEFAULT NULL
) DEFAULT CHARSET=utf8;

# import data for year 3 IDG targets
INSERT INTO _TEMP VALUES
('ADCK1', 'Kinase'),
('ADCK2', 'Kinase'),
('ADCK5', 'Kinase'),
('ALPK2', 'Kinase'),
('ALPK3', 'Kinase'),
('BCKDK', 'Kinase'),
('BRSK1', 'Kinase'),
('CAMK1D', 'Kinase'),
('CAMK1G', 'Kinase'),
('CAMKK1', 'Kinase'),
('CAMKV', 'Kinase'),
('CDC42BPA', 'Kinase'),
('CDC42BPB', 'Kinase'),
('CDC42BPG', 'Kinase'),
('CDK10', 'Kinase'),
('CDK11A', 'Kinase'),
('CDK11B', 'Kinase'),
('CDK12', 'Kinase'),
('CDK13', 'Kinase'),
('CDK14', 'Kinase'),
('CDK15', 'Kinase'),
('CDK16', 'Kinase'),
('CDK17', 'Kinase'),
('CDK18', 'Kinase'),
('CDK19', 'Kinase'),
('CDK20', 'Kinase'),
('CDKL1', 'Kinase'),
('CDKL2', 'Kinase'),
('CDKL3', 'Kinase'),
('CDKL4', 'Kinase'),
('CLK3', 'Kinase'),
('CLK4', 'Kinase'),
('COQ8A', 'Kinase'),
('COQ8B', 'Kinase'),
('CSNK1A1L', 'Kinase'),
('CSNK1G1', 'Kinase'),
('CSNK1G2', 'Kinase'),
('CSNK1G3', 'Kinase'),
('CSNK2A3', 'Kinase'),
('DCLK3', 'Kinase'),
('DSTYK', 'Kinase'),
('DYRK1B', 'Kinase'),
('DYRK2', 'Kinase'),
('DYRK3', 'Kinase'),
('DYRK4', 'Kinase'),
('EEF2K', 'Kinase'),
('ERN2', 'Kinase'),
('HIPK1', 'Kinase'),
('HIPK3', 'Kinase'),
('HIPK4', 'Kinase'),
('ICK', 'Kinase'),
('LMTK2', 'Kinase'),
('LMTK3', 'Kinase'),
('LRRK1', 'Kinase'),
('LTK', 'Kinase'),
('MAP3K10', 'Kinase'),
('MAP3K14', 'Kinase'),
('MAP3K15', 'Kinase'),
('MAP3K21', 'Kinase'),
('MAPK15', 'Kinase'),
('MAPK4', 'Kinase'),
('MARK1', 'Kinase'),
('MARK3', 'Kinase'),
('MARK4', 'Kinase'),
('MAST2', 'Kinase'),
('MAST3', 'Kinase'),
('MAST4', 'Kinase'),
('MKNK2', 'Kinase'),
('NEK1', 'Kinase'),
('NEK10', 'Kinase'),
('NEK11', 'Kinase'),
('NEK3', 'Kinase'),
('NEK4', 'Kinase'),
('NEK5', 'Kinase'),
('NEK6', 'Kinase'),
('NEK7', 'Kinase'),
('NEK9', 'Kinase'),
('NIM1K', 'Kinase'),
('NRBP2', 'Kinase'),
('NRK', 'Kinase'),
('NUAK2', 'Kinase'),
('PAK3', 'Kinase'),
('PAK5', 'Kinase'),
('PAK6', 'Kinase'),
('PAN3', 'Kinase'),
('PDIK1L', 'Kinase'),
('PHKG1', 'Kinase'),
('PHKG2', 'Kinase'),
('PI4KA', 'Kinase'),
('PIK3C2B', 'Kinase'),
('PIK3C2G', 'Kinase'),
('PIP4K2C', 'Kinase'),
('PIP5K1A', 'Kinase'),
('PIP5K1B', 'Kinase'),
('PIP5K1C', 'Kinase'),
('PKMYT1', 'Kinase'),
('PKN3', 'Kinase'),
('PNCK', 'Kinase'),
('POMK', 'Kinase'),
('PRKACB', 'Kinase'),
('PRKACG', 'Kinase'),
('PRPF4B', 'Kinase'),
('PSKH1', 'Kinase'),
('PSKH2', 'Kinase'),
('PXK', 'Kinase'),
('RIOK1', 'Kinase'),
('RIOK2', 'Kinase'),
('RIOK3', 'Kinase'),
('RPS6KC1', 'Kinase'),
('RPS6KL1', 'Kinase'),
('SBK2', 'Kinase'),
('SBK3', 'Kinase'),
('SCYL2', 'Kinase'),
('SCYL3', 'Kinase'),
('SGK494', 'Kinase'),
('SRPK3', 'Kinase'),
('STK17A', 'Kinase'),
('STK17B', 'Kinase'),
('STK19', 'Kinase'),
('STK3', 'Kinase'),
('STK31', 'Kinase'),
('STK32A', 'Kinase'),
('STK32B', 'Kinase'),
('STK32C', 'Kinase'),
('STK33', 'Kinase'),
('STK36', 'Kinase'),
('STK38L', 'Kinase'),
('STK40', 'Kinase'),
('STKLD1', 'Kinase'),
('TAOK1', 'Kinase'),
('TAOK2', 'Kinase'),
('TBCK', 'Kinase'),
('TESK1', 'Kinase'),
('TESK2', 'Kinase'),
('TLK1', 'Kinase'),
('TLK2', 'Kinase'),
('TP53RK', 'Kinase'),
('TSSK1B', 'Kinase'),
('TSSK2', 'Kinase'),
('TSSK3', 'Kinase'),
('TSSK4', 'Kinase'),
('TSSK6', 'Kinase'),
('TTBK1', 'Kinase'),
('TTBK2', 'Kinase'),
('ULK4', 'Kinase'),
('VRK2', 'Kinase'),
('VRK3', 'Kinase'),
('WEE2', 'Kinase'),
('WNK2', 'Kinase'),
('WNK3', 'Kinase'),
('ADGRA1', 'GPCR'),
('ADGRA3', 'GPCR'),
('ADGRB2', 'GPCR'),
('ADGRB3', 'GPCR'),
('ADGRD1', 'GPCR'),
('ADGRD2', 'GPCR'),
('ADGRE1', 'GPCR'),
('ADGRE3', 'GPCR'),
('ADGRF1', 'GPCR'),
('ADGRF2', 'GPCR'),
('ADGRF3', 'GPCR'),
('ADGRF4', 'GPCR'),
('ADGRF5', 'GPCR'),
('ADGRG2', 'GPCR'),
('ADGRG3', 'GPCR'),
('ADGRG4', 'GPCR'),
('ADGRG5', 'GPCR'),
('ADGRG7', 'GPCR'),
('FZD10', 'GPCR'),
('GNRHR2', 'GPCR'),
('GPR101', 'GPCR'),
('GPR12', 'GPCR'),
('GPR135', 'GPCR'),
('GPR137', 'GPCR'),
('GPR139', 'GPCR'),
('GPR141', 'GPCR'),
('GPR142', 'GPCR'),
('GPR146', 'GPCR'),
('GPR149', 'GPCR'),
('GPR150', 'GPCR'),
('GPR151', 'GPCR'),
('GPR152', 'GPCR'),
('GPR153', 'GPCR'),
('GPR156', 'GPCR'),
('GPR157', 'GPCR'),
('GPR160', 'GPCR'),
('GPR162', 'GPCR'),
('GPR171', 'GPCR'),
('GPR173', 'GPCR'),
('GPR174', 'GPCR'),
('GPR18', 'GPCR'),
('GPR19', 'GPCR'),
('GPR20', 'GPCR'),
('GPR21', 'GPCR'),
('GPR22', 'GPCR'),
('GPR25', 'GPCR'),
('GPR26', 'GPCR'),
('GPR27', 'GPCR'),
('GPR3', 'GPCR'),
('GPR31', 'GPCR'),
('GPR32', 'GPCR'),
('GPR34', 'GPCR'),
('GPR37L1', 'GPCR'),
('GPR4', 'GPCR'),
('GPR45', 'GPCR'),
('GPR52', 'GPCR'),
('GPR6', 'GPCR'),
('GPR61', 'GPCR'),
('GPR62', 'GPCR'),
('GPR63', 'GPCR'),
('GPR65', 'GPCR'),
('GPR68', 'GPCR'),
('GPR75', 'GPCR'),
('GPR78', 'GPCR'),
('GPR82', 'GPCR'),
('GPR85', 'GPCR'),
('GPR87', 'GPCR'),
('GPR88', 'GPCR'),
('GPRC5A', 'GPCR'),
('GPRC5B', 'GPCR'),
('GPRC5C', 'GPCR'),
('GPRC5D', 'GPCR'),
('HCAR1', 'GPCR'),
('HCAR3', 'GPCR'),
('LPAR6', 'GPCR'),
('MRGPRE', 'GPCR'),
('MRGPRF', 'GPCR'),
('MRGPRG', 'GPCR'),
('MRGPRX1', 'GPCR'),
('MRGPRX2', 'GPCR'),
('MRGPRX3', 'GPCR'),
('MRGPRX4', 'GPCR'),
('NPBWR1', 'GPCR'),
('NPBWR2', 'GPCR'),
('OXER1', 'GPCR'),
('OXGR1', 'GPCR'),
('P2RY10', 'GPCR'),
('PROKR1', 'GPCR'),
('QRFPR', 'GPCR'),
('RXFP4', 'GPCR'),
('TAAR2', 'GPCR'),
('TAAR3P', 'GPCR'),
('TAAR8', 'GPCR'),
('TAAR9', 'GPCR'),
('TAS2R1', 'GPCR'),
('TAS2R10', 'GPCR'),
('TAS2R13', 'GPCR'),
('TAS2R14', 'GPCR'),
('TAS2R16', 'GPCR'),
('TAS2R19', 'GPCR'),
('TAS2R20', 'GPCR'),
('TAS2R3', 'GPCR'),
('TAS2R30', 'GPCR'),
('TAS2R31', 'GPCR'),
('TAS2R39', 'GPCR'),
('TAS2R4', 'GPCR'),
('TAS2R40', 'GPCR'),
('TAS2R41', 'GPCR'),
('TAS2R42', 'GPCR'),
('TAS2R43', 'GPCR'),
('TAS2R46', 'GPCR'),
('TAS2R5', 'GPCR'),
('TAS2R50', 'GPCR'),
('TAS2R60', 'GPCR'),
('TAS2R7', 'GPCR'),
('TAS2R8', 'GPCR'),
('TAS2R9', 'GPCR'),
('ASIC4', 'Ion Channel'),
('BEST4', 'Ion Channel'),
('CACNA2D2', 'Ion Channel'),
('CACNA2D3', 'Ion Channel'),
('CACNA2D4', 'Ion Channel'),
('CACNG1', 'Ion Channel'),
('CACNG3', 'Ion Channel'),
('CACNG4', 'Ion Channel'),
('CACNG5', 'Ion Channel'),
('CACNG6', 'Ion Channel'),
('CACNG7', 'Ion Channel'),
('CACNG8', 'Ion Channel'),
('CALHM4', 'Ion Channel'),
('CALHM5', 'Ion Channel'),
('CALHM6', 'Ion Channel'),
('CATSPER2', 'Ion Channel'),
('CHRNA10', 'Ion Channel'),
('CHRNB1', 'Ion Channel'),
('CLCA4', 'Ion Channel'),
('CLCC1', 'Ion Channel'),
('CLCN6', 'Ion Channel'),
('CLIC6', 'Ion Channel'),
('GABRP', 'Ion Channel'),
('GPR89A', 'Ion Channel'),
('GPR89B', 'Ion Channel'),
('GRID1', 'Ion Channel'),
('KCNA6', 'Ion Channel'),
('KCNA7', 'Ion Channel'),
('KCNAB2', 'Ion Channel'),
('KCNAB3', 'Ion Channel'),
('KCND1', 'Ion Channel'),
('KCNG2', 'Ion Channel'),
('KCNG3', 'Ion Channel'),
('KCNG4', 'Ion Channel'),
('KCNH4', 'Ion Channel'),
('KCNH6', 'Ion Channel'),
('KCNH8', 'Ion Channel'),
('KCNJ15', 'Ion Channel'),
('KCNJ18', 'Ion Channel'),
('KCNK12', 'Ion Channel'),
('KCNK7', 'Ion Channel'),
('KCNMB3', 'Ion Channel'),
('KCNN1', 'Ion Channel'),
('KCNS1', 'Ion Channel'),
('KCNS2', 'Ion Channel'),
('LRRC38', 'Ion Channel'),
('LRRC55', 'Ion Channel'),
('PKD1L2', 'Ion Channel'),
('PKD1L3', 'Ion Channel'),
('PKD2L2', 'Ion Channel'),
('PLLP', 'Ion Channel'),
('SCN7A', 'Ion Channel'),
('SLC26A1', 'Ion Channel'),
('TMC3', 'Ion Channel'),
('TMC4', 'Ion Channel'),
('TMC5', 'Ion Channel'),
('TMC7', 'Ion Channel'),
('TMEM38B', 'Ion Channel'),
('TMEM63A', 'Ion Channel'),
('TMEM63B', 'Ion Channel'),
('TTYH1', 'Ion Channel'),
('TTYH2', 'Ion Channel');

# update list type table
Insert into ncats_idg_list_type values
(2,'Year 3');

# update list table
Insert into ncats_idg_list
select
    null as id,
    (Select id from protein where sym = _TEMP.symbol) as protein_id,
    _TEMP.symbol as symbol,
    _TEMP.family as family,
    2 as idg_list
from _TEMP;

Drop table _TEMP;