import {Field, ModelList, ReadableModel, use} from "./readableConfig";

export class TargetModelConfig extends ReadableModel {
    readonly name = "Target";
    readonly table = "protein";
    readonly keyColumn = "id";

    readonly sequenceQueryCoverage = new Field("Sequence Query Coverage", "sequence_search_summary", "qcovs", "Query coverage for all alignments between the query sequence and the subject sequence", {schema: "result_cache", requirement: "sequence", dataType: "numeric", binSize: 5});
    readonly sequencePercentIdentical = new Field("Sequence Percent Identical", "sequence_search_summary", "pident", "Percentage of identical matches between the query sequence and the best alignment to the subject sequence", {schema: "result_cache", requirement: "sequence", dataType: "numeric", binSize: 5});
    readonly sequenceBitScore = new Field("Sequence Bit Score", "sequence_search_summary", "bitscore", "Maximum bit score for alignments between the query seqeunce and the subject sequence", {schema: "result_cache", requirement: "sequence", dataType: "numeric", binSize: 100});
    readonly targetDevelopmentLevel = new Field("Target Development Level", "target", "tdl", "Development levels of targets in the list. The categories are based on the degree to which the targets are studied, as evidenced by publications, tool compounds, and other features.", {singleResponse: true});
    readonly nihTargetLists = new Field("NIH Target Lists", "nih_list_type", "list_type", "Lists of proteins defined by the <a href=\"https://druggablegenome.net/IDGProteinList\" target=\"_blank\">IDG Consortium</a>, and recent R03 FOAs.");
    readonly logNovelty = new Field("Log Novelty", "protein", "novelty", "Metric for the relative scarcity of specific publications for targets in the list. See <a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5870731/\" target=\"_blank\">reference</a> for details.", {dataType: "numeric", binSize: 0.5, log: true, singleResponse: true});
    readonly logPubmedScore = new Field("Log PubMed Score", "tdl_info", "number_value", "Metric for the frequency of targets in the list in the scientific literature.", {whereClause: "tdl_info.itype = 'JensenLab PubMed Score'", dataType: "numeric", binSize: 0.5, log: true, singleResponse: true});
    readonly idgFamily = new Field("IDG Family", "target", "fam", "Target family designations generated by IDG-KMC groups at UNM and UMiami.", {select: "case target.fam when 'IC' then 'Ion Channel' when 'TF; Epigenetic' then 'TF-Epigenetic' when 'TF' then 'Transcription Factor' when 'NR' then 'Nuclear Receptor' else if(target.fam is null,'Other',target.fam) end", singleResponse: true});
    readonly pantherClass = new Field("PANTHER Class", "panther_class", "name", "Classification of targets into hierarchical families according to the <a href=\"http://www.pantherdb.org/\" target=\"_blank\">PANTHER classification system</a>.");
    readonly dtoClass = new Field("DTO Class", "dto", "name", "Classification of targets into hierarchical families according to the <a href=\"http://drugtargetontology.org/\" target=\"_blank\">Drug Target Ontology</a>.", {whereClause: "dto.name != 'protein'"});
    readonly reactomePathway = new Field("Reactome Pathway", "pathway", "name", "Biochemical pathways containing targets in the list, based on data from <a href=\"http://www.reactome.org/\" target=\"_blank\">Reactome</a>.", {whereClause: "pathway.pwtype = 'Reactome'"});
    readonly goProcess = new Field("GO Process", "goa", "go_term_text", "Cellular processes involving targets in the list, as defined by <a href=\"https://www.uniprot.org/help/gene_ontology/\" target=\"_blank\">UniProt</a>.", {whereClause: "go_type = 'Process'"});
    readonly goComponent = new Field("GO Component", "goa", "go_term_text", "Cellular locations containing targets in the list, as defined by <a href=\"https://www.uniprot.org/help/gene_ontology/\" target=\"_blank\">UniProt</a>.", {whereClause: "go_type = 'Component'"});
    readonly goFunction = new Field("GO Function", "goa", "go_term_text", "Cellular functions of targets in the list, as defined by <a href=\"https://www.uniprot.org/help/gene_ontology/\" target=\"_blank\">UniProt</a>.", {whereClause: "go_type = 'Function'"});
    readonly associatedDiseaseField = new Field("Associated Disease", "ncats_disease", "name", "Diseases found to be associated with targets in the list, based on a documented indication in data from any source.");
    readonly diseaseSubtree = new Field("Disease Subtree", "ancestry_mondo", "ancestor_id", "Ancestor terms from MONDO for diseases associated with targets in the list.", {select: "(select name from mondo where mondo.mondoid = ancestry_mondo.ancestor_id)", filterSelect: "ancestry_mondo.ancestor_id", aliases: ["Disease Ancestry"]});
    readonly jaxMgiPhenotype = new Field("JAX/MGI Phenotype", "phenotype", "term_name", "Phenotypes associated with targets in the list, based on data from <a href=\"http://www.informatics.jax.org/\" target=\"_blank\">Mouse Genome Informatics (MGI)</a>.", {whereClause: "phenotype.ptype = 'JAX/MGI Human Ortholog Phenotype'"});
    readonly gwas = new Field("GWAS", "tiga", "trait", "Diseases and other genetic traits known to be associated with targets in the list, according to data from <a href=\"https://www.ebi.ac.uk/gwas\" target=\"_blank\">GWAS Catalog</a>.");
    readonly idgResourceType = new Field("IDG Resource Type", "drgc_resource", "resource_type", "Resource types generated by IDG partners");
    readonly uniprotKeyword = new Field("UniProt Keyword", "xref", "xtra", "A classifications of targets into multiple categories with a controlled vocabulary defined by <a href=\"https://www.uniprot.org/help/keywords\" target=\"_blank\">UniProt</a>.", {whereClause: "xref.xtype = 'UniProt Keyword'"});
    readonly ortholog = new Field("Ortholog", "ortholog", "species", "Species which are known to have analogs to the targets in the list, based on data from <a href=\"https://www.genenames.org/\" target=\"_blank\">HGNC</a>.");
    readonly impcPhenotype = new Field("IMPC Phenotype", "phenotype", "term_name", "Phenotypes associated with targets in the list, based on data from <a href=\"https://www.mousephenotype.org/\" target=\"_blank\">International Mouse Phenotyping Consortium (IMPC)</a>.", {whereClause: "phenotype.ptype = 'IMPC' and phenotype.p_value < 0.05"});
    readonly expression = new Field("Expression", "tissue", "name", "Tissues expressing targets in the list, based on protein expression data and RNA expression data from a number of data sources.", {whereClause: "expression.expressed = true"});
    readonly wikipathwaysPathway = new Field("WikiPathways Pathway", "pathway", "name", "Biochemical pathways containing targets in the list, based on data from <a href=\"http://www.wikipathways.org/\" target=\"_blank\">WikiPathways</a>.", {whereClause: "pathway.pwtype = 'WikiPathways'"});
    readonly keggPathway = new Field("KEGG Pathway", "pathway", "name", "Biochemical pathways containing targets in the list, based on data from <a href=\"https://www.genome.jp/kegg/pathway.html\" target=\"_blank\">Kyoto Encyclopedia of Genes and Genomes (KEGG)</a>.", {whereClause: "pathway.pwtype = 'KEGG'"});
    readonly interactingViralProtein = new Field("Interacting Viral Protein", "viral_protein", "name", "Viruses proteins that interact, or are predicted to interact, with targets in the list, based on data from <a href=\"http://phipster.org/\" target=\"_blank\">P-HIPSTer</a>.", {whereClause: "viral_ppi.highConfidence = 1"});
    readonly interactingVirus = new Field("Interacting Virus", "virus", "name", "Viruses that interact, or are predicted to interact, with targets in the list, based on data from <a href=\"http://phipster.org/\" target=\"_blank\">P-HIPSTer</a>.", {whereClause: "viral_ppi.highConfidence = 1"});
    readonly dataSource = new Field("Data Source", "ncats_dataSource_map", "dataSource", "Data Sources contributing data to the targets in the list.");
    readonly uniprotPathway = new Field("UniProt Pathway", "pathway", "name", "Biochemical pathways containing targets in the list, based on data from <a href=\"https://www.uniprot.org/\" target=\"_blank\">UniProt</a>.", {whereClause: "pathway.pwtype = 'UniProt'"});
    readonly pathwaycommonsPathway = new Field("PathwayCommons Pathway", "pathway", "name", "Biochemical pathways containing targets in the list, based on data from <a href=\"https://www.pathwaycommons.org/\" target=\"_blank\">PathwayCommons</a>.", {whereClause: "pathway.pwtype like 'PathwayCommons: %'"});
    readonly stringdbInteractionScore = new Field("StringDB Interaction Score", "ncats_ppi", "score", "Metric for the confidence in the protein-protein interaction between the associated target and the targets in the list, as mined and calculated by <a href=\"https://string-db.org/\" target=\"_blank\">STRING</a>.", {select: "ncats_ppi.score / 1000", dataType: "numeric", binSize: 0.02});
    readonly bioplexInteractionProbability = new Field("BioPlex Interaction Probability", "ncats_ppi", "p_int", "Metric for the confidence in the protein-protein interaction between the associated target and the targets in the list, as determined by <a href=\"https://bioplex.hms.harvard.edu/\" target=\"_blank\">BioPlex Interactome</a>.", {dataType: "numeric", binSize: 0.01});
    readonly ppiDataSource = new Field("PPI Data Source", "ncats_ppi", "ppitypes", "Data Sources reporting interactions between the associated target and targets in the list.", {whereClause: "ncats_ppi.ppitypes != 'mock'"});
    readonly jensenlabConfidence = new Field("JensenLab Confidence", "disease", "conf", "Metric for the confidence in the disease association, as mined and calculated by <a href=\"https://diseases.jensenlab.org/Search\" target=\"_blank\">DISEASES</a>.", {dataType: "numeric", binSize: 0.1});
    readonly expressionAtlasLog2FoldChange = new Field("Expression Atlas Log2 Fold Change", "disease", "log2foldchange", "Quantified value for the change in expression level of targets in the list in the disease state, as reported by <a href=\"https://www.ebi.ac.uk/gxa/\" target=\"_blank\">Expression Atlas</a>.", {dataType: "numeric", binSize: 0.5});
    readonly disgenetScore = new Field("DisGeNET Score", "disease", "score", "Metric to quantify the disease association, accounting for number of data sources, level of curation, number of publications, etc., as calculated by <a href=\"https://www.disgenet.org/home/\" target=\"_blank\">DisGeNET</a>.", {dataType: "numeric", binSize: 0.02});
    readonly diseaseDataSource = new Field("Disease Data Source", "disease", "dtype", "The data source of the association between disease and target.");
    readonly linkedDisease = new Field("Linked Disease", "ncats_disease", "name", "Diseases linked to targets in the list, which may be descendents of the disease used in the query.");
    readonly jensenlabTextminingZscore = new Field("JensenLab TextMining zscore", "disease", "zscore", "", {dataType: "numeric", binSize: 0.1});
    readonly predictedActivity = new Field("Predicted Activity", "predictor_results", "result", "Predicted activity of the query structure against the targets in the list (-log M)", {schema: "result_cache", requirement: "associatedSmiles", dataType: "numeric", binSize: 0.1});
    readonly predictionApplicability = new Field("Prediction Applicability", "predictor_results", "similarity", "Confidence in the prediction result, calculated as the Tanimoto similarity of the query structure to structures in the training set. Confidence of 1 means the query structure is part of the training set.", {schema: "result_cache", requirement: "associatedSmiles", dataType: "numeric", binSize: 0.1});
    readonly action = new Field("Action", "ncats_ligand_activity", "action_type", "Modes of action documented for targets in the list against the associated ligand.", {requirement: "associatedLigand", whereClause: "ncats_ligand_activity.action_type is not null"});
    readonly potency = new Field("Potency", "ncats_ligand_activity", "act_value", "Measured potency values (-log M) for targets in the list against the associated ligand. Values may be EC50, IC50, Kd, Ki.", {requirement: "associatedLigand", dataType: "numeric", binSize: 0.1});
    readonly activity = new Field("Activity", "ncats_ligand_activity", "act_type", "Measurement types recorded for targets in the list against the associated ligand.", {requirement: "associatedLigand", whereClause: "ncats_ligand_activity.act_type not in ('','-')"});
    readonly uniprot = new Field("UniProt", "protein", "uniprot", "The UniProt ID for this protein", {singleResponse: true});
    readonly symbol = new Field("Symbol", "protein", "sym", "The approved gene symbol", {singleResponse: true});
    readonly nameField = new Field("Name", "target", "name", "The name of the protein", {singleResponse: true});
    readonly novelty = new Field("Novelty", "protein", "novelty", "Tin-X metric for the relative scarcity of specific publications for this target.", {singleResponse: true});
    readonly externalFamily = new Field("External Family", "target", "famext", "", {singleResponse: true});
    readonly pdbIds = new Field("PDB IDs", "xref", "value", "A comma separated list of PDB IDs for structures for the target", {whereClause: "xref.xtype = 'PDB'", groupMethod: "group_concat", singleResponse: true});
    readonly ncbiGeneSummary = new Field("NCBI Gene Summary", "tdl_info", "string_value", "A summary of knowledge about the gene from NCBI", {whereClause: "tdl_info.itype = 'NCBI Gene Summary'"});
    readonly antibodyCount = new Field("Antibody Count", "tdl_info", "integer_value", "Count of Antibodies to this protein", {whereClause: "tdl_info.itype = 'Ab Count'", singleResponse: true});
    readonly pubmedScore = new Field("PubMed Score", "tdl_info", "number_value", "Sum of Jensen Lab generated fractional counting scores for the prevalence of this target in PubMed articles.", {whereClause: "tdl_info.itype = 'JensenLab PubMed Score'", singleResponse: true});
    readonly pubtatorScore = new Field("PubTator Score", "tdl_info", "number_value", "Sum of the PubTator scores, a score based on text mining PubMed data.", {whereClause: "tdl_info.itype = 'PubTator Score'", singleResponse: true});
    readonly uniprotFunction = new Field("UniProt Function", "tdl_info", "string_value", "Description of the function of the protein, from UniProt.", {whereClause: "tdl_info.itype = 'UniProt Function'"});
    readonly tcrdid = new Field("TCRDID", "target", "id", "An internal ID for the target", {singleResponse: true});
    readonly preferredSymbol = new Field("Preferred Symbol", "protein", "preferred_symbol", "The preferred symbol to use for this target, usually the gene symbol, but falls back on the uniprot ID if there is no gene symbol, or if the gene symbol is not unique amongst targets.", {singleResponse: true});
    readonly sequence = new Field("Sequence", "protein", "seq", "The amino acid sequence of the protein", {singleResponse: true});
    readonly ppiDataSource2 = new Field("PPI Data Source", "ncats_ppi", "ppitypes", "Data Sources reporting interactions between the associated target and targets in the list.");
    readonly bioplexPNi = new Field("BioPlex p_ni", "ncats_ppi", "p_ni", "BioPlex score representing the probability that the interaction detected was non-specific.");
    readonly bioplexPWrong = new Field("BioPlex p_wrong", "ncats_ppi", "p_wrong", "BioPlex score representing the probability that the interacting protein was wrongly identified.");
    readonly diseaseSourceCount = new Field("Disease Source Count", "disease", "dtype", "Count of data sources contributing evidence for the disease - target association", {requirement: "associatedDisease", groupMethod: "count"});
    readonly activityValues = new Field("Activity Values", "ncats_ligand_activity", "act_value", "Activity values (-log M) for the ligand target interaction. There may be multiple values reported for each ligand target pair.", {requirement: "associatedLigand", select: "concat(ncats_ligand_activity.act_type,  ' ', round(ncats_ligand_activity.act_value,2)) separator ', '", groupMethod: "group_concat"});
    readonly averageActivityValue = new Field("Average Activity Value", "ncats_ligand_activity", "act_value", "Average measured activity value (-log M) for the ligand target interaction.", {requirement: "associatedLigand", groupMethod: "avg", dataType: "numeric", binSize: 0.1});
    readonly ligandActions = new Field("Ligand Actions", "ncats_ligand_activity", "action_type", "Mode of action documented for the targeet against the associated ligand.", {requirement: "associatedLigand", groupMethod: "group_concat"});
    readonly predictionTrainingSmiles = new Field("Prediction Training Smiles", "predictor_results", "neighbor_smiles", "Structure from the training set that most closely matches the query structure.", {schema: "result_cache", requirement: "associatedSmiles"});
    readonly predictionTrainingActivity = new Field("Prediction Training Activity", "predictor_results", "neighbor_activity", "Activity value from the training set for the structure that most closely matches the query structure.", {schema: "result_cache", requirement: "associatedSmiles", select: "concat(predictor_results.neighbor_activity,  ' ', predictor_results.neighbor_unit)"});
    readonly predictionModelName = new Field("Prediction Model Name", "predictor_results", "model_name", "Name of the QSAR model that generated the drug target activity prediction.", {schema: "result_cache", requirement: "associatedSmiles"});
    readonly predictionTargetChemblId = new Field("Prediction Target Chembl ID", "predictor_results", "target_chembl_id", "Chembl ID for the target", {schema: "result_cache", requirement: "associatedSmiles"});
    readonly uniprotKeywordId = new Field("UniProt Keyword ID", "xref", "value", "The ID of the UniProt Keyword", {whereClause: "xref.xtype = 'UniProt Keyword'"});
    readonly drug = new Field("Drug", "disease", "drug_name", "Drugs associated with diseases in the list, based on indication data from <a href=\"https://drugcentral.org/\" target=\"_blank\">DrugCentral</a>.", {whereClause: "disease.drug_name is not null"});
    readonly ppiUniprot = new Field("PPI UniProt", "protein", "uniprot", "UniProt ID of the the interacting protein", {whereClause: "protein.id = ncats_ppi.other_id"});
    readonly ppiSymbol = new Field("PPI Symbol", "protein", "sym", "Gene Symbol of the interacting protein", {whereClause: "protein.id = ncats_ppi.other_id"});
    readonly gardRare = new Field("GARD Rare", "ncats_disease", "gard_rare", "Annotation from GARD as to whether the disease meets the criteria to be considered a rare disease.", {singleResponse: true});
    readonly associatedDiseaseEvidence = new Field("Associated Disease Evidence", "disease", "evidence", "A note from the data source regarding the evidence behind the association between disease and target.");
    readonly associatedDiseaseDrugName = new Field("Associated Disease Drug Name", "disease", "drug_name", "Based on data from DrugCentral, these are the names of drugs whose indication has yielded this association between disease and target.");
    readonly associatedDiseasePValue = new Field("Associated Disease P-value", "disease", "pvalue", "The significance of the association between disease and target based on the Expression Atlas log2foldchange.");
    readonly associatedDiseaseSource = new Field("Associated Disease Source", "disease", "source", "A note from DisGeNET or eRAM regarding the dataset which supplied the data.");
    readonly associatedDiseaseSourceId = new Field("Associated Disease Source ID", "disease", "did", "The disease ID used by the data source for this disease association");
    readonly monarchS2o = new Field("Monarch S2O", "disease", "S2O", "A measure from Monarch quantifying the association betweeen disease and target.");
    readonly mondoId = new Field("Mondo ID", "ncats_disease", "mondoid", "Mondo Identifier", {singleResponse: true});
    readonly pantherClassId = new Field("PANTHER Class ID", "panther_class", "pcid", "The ID of the PANTHER class");
    readonly dtoId = new Field("DTO ID", "dto", "dtoid", "The ID of the DTO class", {whereClause: "dto.name != 'protein'"});
    readonly dtoDefinition = new Field("DTO Definition", "dto", "def", "The descriptive definition of the DTO class", {whereClause: "dto.name != 'protein'"});
    readonly enspId = new Field("ENSP ID", "protein", "stringid", "");
    readonly proteinAlias = new Field("Protein Alias", "alias", "value", "", {groupMethod: "group_concat"});
    readonly ensemblId = new Field("Ensembl ID", "xref", "value", "", {whereClause: "xref.xtype='Ensembl'", groupMethod: "group_concat"});
    readonly sequenceId = new Field("Sequence ID", "sequence_search_results", "sseqid", "Subject sequence ID from blastp", {schema: "result_cache", requirement: "sequence"});
    readonly percentIdentical = new Field("Percent Identical", "sequence_search_results", "pident", "Percentage of identical matches between the query sequence and the subject sequence", {schema: "result_cache", requirement: "sequence"});
    readonly alignmentLength = new Field("Alignment Length", "sequence_search_results", "length", "Length of the alignment", {schema: "result_cache", requirement: "sequence"});
    readonly mismatchCount = new Field("Mismatch Count", "sequence_search_results", "mismatch", "Count of mismatched residues between the query sequence and the subject sequence", {schema: "result_cache", requirement: "sequence"});
    readonly gapCount = new Field("Gap Count", "sequence_search_results", "gapopen", "Count of gap openings in the alignment", {schema: "result_cache", requirement: "sequence"});
    readonly querySequenceStart = new Field("Query Sequence Start", "sequence_search_results", "qstart", "Location on the query sequence where the alignment starts", {schema: "result_cache", requirement: "sequence"});
    readonly querySequenceEnd = new Field("Query Sequence End", "sequence_search_results", "qend", "Location on the query sequence where the alignment ends", {schema: "result_cache", requirement: "sequence"});
    readonly subjectSequenceStart = new Field("Subject Sequence Start", "sequence_search_results", "sstart", "Location on the subject sequence where the alignment starts", {schema: "result_cache", requirement: "sequence"});
    readonly subjectSequenceEnd = new Field("Subject Sequence End", "sequence_search_results", "send", "Location on the subject sequence where the alignment ends", {schema: "result_cache", requirement: "sequence"});
    readonly expectValue = new Field("Expect Value", "sequence_search_results", "evalue", "Expect value for the alignment, which measures the chance of finding a particular alignment by random chance in a database of this size.", {schema: "result_cache", requirement: "sequence"});
    readonly bitScore = new Field("Bit Score", "sequence_search_results", "bitscore", "Another measure of sequence similarity, which is independent of query length and database size.", {schema: "result_cache", requirement: "sequence"});
    readonly queryAlignment = new Field("Query Alignment", "sequence_search_results", "qseq", "The aligned part of the query sequence", {schema: "result_cache", requirement: "sequence"});
    readonly subjectAlignment = new Field("Subject Alignment", "sequence_search_results", "sseq", "The aligned part of the subject sequence", {schema: "result_cache", requirement: "sequence"});
    readonly pubmedScore2 = new Field("Pubmed Score", "pmscore", "score", "Jensen Lab generated fractional counting score for the prevalence of this target in PubMed articles.");
    readonly pubmedScoreYear = new Field("Pubmed Score Year", "pmscore", "year", "The corresponding year for the Pubmed Score");
    readonly pathwayType = new Field("Pathway Type", "pathway", "pwtype", "The data source that assigned the pathway");
    readonly pathwayName = new Field("Pathway Name", "pathway", "name", "The name of the pathway");
    readonly pathwayUrl = new Field("Pathway URL", "pathway", "url", "A URL provided by the data source for this pathway");
    readonly pathwaySourceId = new Field("Pathway Source ID", "pathway", "id_in_source", "The ID of the pathway in the referring data source");
    readonly ligandName = new Field("Ligand Name", "ncats_ligands", "name", "The name of the ligand", {singleResponse: true});
    readonly ligandIsDrug = new Field("Ligand Is Drug", "ncats_ligands", "isDrug", "Whether or not the ligand is an approved drug", {singleResponse: true});
    readonly ligandSmiles = new Field("Ligand SMILES", "ncats_ligands", "smiles", "SMILES string for the ligand", {singleResponse: true});
    readonly ligandPubchemId = new Field("Ligand PubChem ID", "ncats_ligands", "PubChem", "PubChem ID for the ligand", {singleResponse: true});
    readonly ligandChemblId = new Field("Ligand ChEMBL ID", "ncats_ligands", "ChEMBL", "ChEMBL ID for the ligand", {singleResponse: true});
    readonly ligandGuideToPharmacologyId = new Field("Ligand Guide to Pharmacology ID", "ncats_ligands", "Guide to Pharmacology", "IUPHAR Guide to Pharmacology ID for the ligand", {singleResponse: true});
    readonly ligandDrugcentralId = new Field("Ligand DrugCentral ID", "ncats_ligands", "DrugCentral", "DrugCentral ID for the ligand", {singleResponse: true});
    readonly ligandDescription = new Field("Ligand Description", "ncats_ligands", "description", "A description for the ligand", {singleResponse: true});
    readonly ligandActivity = new Field("Ligand Activity", "ncats_ligand_activity", "act_value", "Activity value measured for the drug against the given target. Units are -log (M), for example 1nM would correspond to a value of 9.");
    readonly ligandActivityType = new Field("Ligand Activity Type", "ncats_ligand_activity", "act_type", "The type of activity value reported, such as IC50, EC50, Ki, Kd, etc.");
    readonly ligandAction = new Field("Ligand Action", "ncats_ligand_activity", "action_type", "The mode of action for the ligand against the target, such as inhibitor, agonist, blocker, etc.");
    readonly ligandReferences = new Field("Ligand References", "ncats_ligand_activity", "reference", "A reference for the ligand activity against the target");
    readonly ligandReferenceSource = new Field("Ligand Reference Source", "ncats_ligand_activity", "reference_source", "The source for the reference");
    readonly ligandPubmedIds = new Field("Ligand PubMed IDs", "ncats_ligand_activity", "pubmed_ids", "A list of pubmed IDs that provided the ligand activity against the target");
    readonly preferredTerm = new Field("Preferred Term", "ncats_ligands", "pt", "The preferred term for the substance", {singleResponse: true});
    readonly unii = new Field("UNII", "ncats_ligands", "unii", "Unique Ingredient Identifier (UNII) for the substance from GSRS", {singleResponse: true});
    readonly goTermType = new Field("GO Term Type", "goa", "go_type", "The type of GO term, i.e. Component, Function, or Process");
    readonly goTerm = new Field("GO Term", "goa", "go_term_text", "The GO term assigned to the target");
    readonly goTermGoId = new Field("GO Term go_id", "goa", "go_id", "The GO terms discrete ID");
    readonly goTermEvidence = new Field("GO Term Evidence", "goa", "evidence", "Evidence categories are defined by GO Consortium. The values shown here represent the evidence for the target's association with the assigned GO term.�");
    readonly goTermAssignedBy = new Field("GO Term Assigned By", "goa", "assigned_by", "The organization that has assigned the GO term to the target");
    readonly nearestTclinDirection = new Field("Nearest Tclin Direction", "kegg_nearest_tclin", "direction", "The direction \"upstream\" or \"downstream\" of the nearest Tclin target");
    readonly nearestTclinDistance = new Field("Nearest Tclin Distance", "kegg_nearest_tclin", "distance", "The distance to the nearest Tclin target");
    readonly nearestTclinSymbol = new Field("Nearest Tclin Symbol", "protein", "uniprot", "The UniProt ID of the nearest Tclin target", {whereClause: "protein.id = kegg_nearest_tclin.tclin_id"});
    readonly nearestTclinUniprot = new Field("Nearest Tclin Uniprot", "protein", "sym", "The gene symbol of the nearest Tclin target", {whereClause: "protein.id = kegg_nearest_tclin.tclin_id"});
    readonly expressionSource = new Field("Expression Source", "expression", "etype", "The data source providing evidence for expression of the target. Different data sources provide expression data on different scales and in different formats.");
    readonly expressionTissue = new Field("Expression Tissue", "tissue", "name", "The tissue for which the expression data corresponds");
    readonly expressionQualitativeValue = new Field("Expression Qualitative Value", "expression", "qual_value", "Qualitative description of the expression level (one of: High, Medium, Low, Not Detected).");
    readonly expressionNumericValue = new Field("Expression Numeric Value", "expression", "number_value", "Numerical value for expression level");
    readonly expressionSourceRank = new Field("Expression Source Rank", "expression", "source_rank", "Rank for this expression value (percentile) from this data source, regardless of the format of the data (i.e. qualitative, numeric, or boolean).");
    readonly expressionEvidence = new Field("Expression Evidence", "expression", "evidence", "Text from the data source about the level or type of evidence for the expression");
    readonly expressionJensenlabOid = new Field("Expression JensenLab OID", "expression", "oid", "A corresponding OID from JensenLab Data Sources");
    readonly expressionUberonId = new Field("Expression Uberon ID", "expression", "uberon_id", "The Uberon ID for the Cell or Tissue for the expression");
    readonly expressionSoureId = new Field("Expression Soure ID", "expression", "source_id", "The ID by which the target was referred in the original data source.");
    readonly pubtatorScore2 = new Field("PubTator Score", "ptscore", "score", "A score based on text mining PubMed data.");
    readonly pubtatorScoreYear = new Field("PubTator Score Year", "ptscore", "year", "The corresponding year for the PubTator Score");
    readonly patentCount = new Field("Patent Count", "patent_count", "count", "A count of patents for the target");
    readonly patentCountYear = new Field("Patent Count Year", "patent_count", "year", "The corresponding year for the Patent Count");
    readonly tinxTargetImportance = new Field("TINX Target Importance", "tinx_importance", "score", "Importance of the target in the disease");
    readonly tinxDisease = new Field("TINX Disease", "tinx_importance", "ncats_disease_id", "Disease name, as referred to by Tin-X", {select: "(select name from ncats_disease where ncats_disease.id = tinx_importance.ncats_disease_id)"});
    readonly tinxDiseaseSummary = new Field("TINX Disease Summary", "tinx_importance", "ncats_disease_id", "Disease summary from Tin-X", {select: "(select do_description from ncats_disease where ncats_disease.id = tinx_importance.ncats_disease_id)"});
    readonly tinxDiseaseDoid = new Field("TINX Disease DOID", "tinx_importance", "doid", "Disease Ontology ID");
    readonly tinxDiseaseNovelty = new Field("TINX Disease Novelty", "tinx_importance", "ncats_disease_id", "Novelty of the disease in publications", {select: "(select novelty from ncats_disease where ncats_disease.id = tinx_importance.ncats_disease_id)"});
    readonly harmonizomeField = new Field("Harmonizome Field", "hgram_cdf", "type", "Harmonizome attribute name");
    readonly harmonizomeAttributeCount = new Field("Harmonizome Attribute Count", "hgram_cdf", "attr_count", "Count of attributes for this protein");
    readonly harmonizomeAttributeCdf = new Field("Harmonizome Attribute CDF", "hgram_cdf", "attr_cdf", "Position of this protein in the cumulative ranking of all proteins for this attribute");
    readonly phenotypeDataSource = new Field("Phenotype Data Source", "phenotype", "ptype", "Data Source contributing the phenotype data");
    readonly trait = new Field("Trait", "phenotype", "trait", "OMIM Trait ID");
    readonly topLevelTermId = new Field("Top Level Term ID", "phenotype", "top_level_term_id", "IMPC ID for the Top Level Trait");
    readonly topLevelTermName = new Field("Top Level Term Name", "phenotype", "top_level_term_name", "IMPC Name for the Top Level Trait");
    readonly termId = new Field("Term ID", "phenotype", "term_id", "ID for the Trait");
    readonly termName = new Field("Term Name", "phenotype", "term_name", "Name for the Trait");
    readonly pValue = new Field("p-value", "phenotype", "p_value", "");
    readonly percentageChange = new Field("Percentage Change", "phenotype", "percentage_change", "");
    readonly effectSize = new Field("Effect Size", "phenotype", "effect_size", "");
    readonly procedureName = new Field("Procedure Name", "phenotype", "procedure_name", "");
    readonly parameterName = new Field("Parameter Name", "phenotype", "parameter_name", "");
    readonly gpAssoc = new Field("GP Assoc", "phenotype", "gp_assoc", "");
    readonly statisticalMethod = new Field("Statistical Method", "phenotype", "statistical_method", "");
    readonly sex = new Field("Sex", "phenotype", "sex", "");
    readonly gtexTissue = new Field("GTEx Tissue", "gtex", "tissue", "Tissue Name, as provided by GTEx");
    readonly tpm = new Field("TPM", "gtex", "tpm", "Median transcripts per million for ALL samples for this gene and tissue");
    readonly tpmMale = new Field("TPM (male)", "gtex", "tpm_male", "Median transcripts per million for MALE samples for this gene and tissue");
    readonly tpmFemale = new Field("TPM (female)", "gtex", "tpm_male_rank", "Median transcripts per million for FEMALE samples for this gene and tissue");
    readonly tpmRank = new Field("TPM Rank", "gtex", "tpm_rank", "Percentile rank for expression of this gene in this tissue based on ALL samples.");
    readonly tpmRankMale = new Field("TPM Rank (male)", "gtex", "tpm_female", "Percentile rank for expression of this gene in this tissue based on MALE samples.");
    readonly tpmRankFemale = new Field("TPM Rank (female)", "gtex", "tpm_female_rank", "Percentile rank for expression of this gene in this tissue based on FEMALE samples.");
    readonly uberonId = new Field("Uberon ID", "gtex", "uberon_id", "Uberon Tissue ID");
    readonly geneRifText = new Field("Gene RIF Text", "generif", "text", "Text of the Gene Reference into Function");
    readonly geneRifDate = new Field("Gene RIF Date", "generif", "date", "Year the GeneRIF was documented");
    readonly geneRifPubmedIds = new Field("Gene RIF Pubmed IDs", "generif2pubmed", "pubmed_id", "Supporting Pubmed IDs to this GeneRIF");
    readonly ncbiGeneId = new Field("NCBI Gene ID", "generif", "gene_id", "NCBI Gene ID for this gene RIF");
    readonly pmid = new Field("PMID", "pubmed", "id", "The pubmed id for this article.", {schema: "ncats_pubmed"});
    readonly title = new Field("Title", "pubmed", "title", "Publication Title", {schema: "ncats_pubmed"});
    readonly journal = new Field("Journal", "pubmed", "journal", "Publication Journal", {schema: "ncats_pubmed"});
    readonly date = new Field("Date", "pubmed", "date", "Publication Date", {schema: "ncats_pubmed"});
    readonly authors = new Field("Authors", "pubmed", "authors", "Authors of the publication", {schema: "ncats_pubmed"});
    readonly source = new Field("Source", "protein2pubmed", "source", "The source that reported that this target was mentioned in this publication. Typically, NCBI data includes publications manually documented as referring to a given target, as well as entity matching to the title and abstract. JensenLab Text Mining mentions include entity matching results for the abstract, and the full text of the article, when available.");
    readonly abstract = new Field("Abstract", "pubmed", "abstract", "", {schema: "ncats_pubmed"});
    readonly tigaEnsgId = new Field("TIGA ENSG ID", "tiga", "ensg", "Ensembl Gene ID that TIGA uses for this gene");
    readonly efoId = new Field("EFO ID", "tiga", "efoid", "EFO ID for the GWAS trait");
    readonly gwasTrait = new Field("GWAS Trait", "tiga", "trait", "GWAS Trait");
    readonly studyCount = new Field("Study Count", "tiga", "n_study", "Count of studies supporting the gene-trait association");
    readonly snpCount = new Field("SNP Count", "tiga", "n_snp", "Count of SNPs involved with gene-trait association");
    readonly weightedSnpCount = new Field("Weighted SNP Count", "tiga", "n_snpw", "Count of SNPs involved with the gene-trait association, weighted by distance (inverse exponential)");
    readonly traitCountForGene = new Field("Trait Count for Gene", "tiga", "geneNtrait", "Count of traits associated with the gene");
    readonly studyCountForGene = new Field("Study Count for Gene", "tiga", "geneNstudy", "Count of studies associated with the gene");
    readonly geneCountForTrait = new Field("Gene Count for Trait", "tiga", "traitNgene", "Count of genes associated with the trait");
    readonly studyCountForTrait = new Field("Study Count for Trait", "tiga", "traitNstudy", "Count of studies associated with the trait");
    readonly medianPValue = new Field("Median p-value", "tiga", "pvalue_mlog_median", "Median value for -Log(pValue) supporting the gene-trait association");
    readonly medianOddsRatio = new Field("Median Odds Ratio", "tiga", "or_median", "Median Odds Ratio (inverted if < 1 ) that support the gene-trait association");
    readonly betaCount = new Field("Beta Count", "tiga", "n_beta", "Count of beta values with 95% confidence intervals supporting the gene-trait association");
    readonly meanStudyN = new Field("Mean Study N", "tiga", "study_N_mean", "Mean sample size of studies supporting gene-trait association");
    readonly rcras = new Field("RCRAS", "tiga", "rcras", "Relative Citation Ratio (iCite RCR) Aggregated Score");
    readonly meanRank = new Field("Mean Rank", "tiga", "meanRank", "Ranking of gene-trait pairs, based on selected variables, determined by benchmarking versus gold standard associations");
    readonly meanRankScore = new Field("Mean Rank Score", "tiga", "meanRankScore", "Mean Rank Score = 100 - Percentile(Mean Rank)");
    readonly tigaDiseaseLink = new Field("TIGA Disease Link", "tiga", "ncats_disease_id", "Internal disease ID mapped to this EFO ID");

    readonly facets = new ModelList("facet", [
            use(this.sequenceQueryCoverage),
            use(this.sequencePercentIdentical),
            use(this.sequenceBitScore),
            use(this.targetDevelopmentLevel),
            use(this.nihTargetLists),
            use(this.logNovelty),
            use(this.logPubmedScore),
            use(this.idgFamily),
            use(this.pantherClass),
            use(this.dtoClass),
            // use(this.reactomePathway),
            // use(this.goProcess),
            // use(this.goComponent),
            // use(this.goFunction),
            // use(this.associatedDiseaseField),
            // use(this.diseaseSubtree),
            // use(this.jaxMgiPhenotype),
            // use(this.gwas),
            // use(this.idgResourceType),
            // use(this.uniprotKeyword, {default: false}),
            // use(this.ortholog, {default: false}),
            // use(this.impcPhenotype, {default: false}),
            // use(this.expression, {default: false}),
            // use(this.wikipathwaysPathway, {default: false}),
            // use(this.keggPathway, {default: false}),
            // use(this.interactingViralProtein, {default: false}),
            // use(this.interactingVirus, {default: false}),
            // use(this.dataSource, {default: false}),
            // use(this.uniprotPathway, {default: false}),
            // use(this.pathwaycommonsPathway, {default: false})
        ]);

    readonly list = new ModelList("list", [
            use(this.tcrdid, {alias: "tcrdid"}),
            use(this.targetDevelopmentLevel, {alias: "tdl"}),
            use(this.idgFamily, {alias: "fam"}),
            use(this.nameField),
            use(this.uniprot, {alias: "uniprot"}),
            use(this.preferredSymbol, {alias: "preferredSymbol"}),
            use(this.symbol, {alias: "sym"}),
            use(this.sequence, {alias: "seq"}),
            use(this.novelty, {alias: "novelty"}),
            use(this.ncbiGeneSummary, {alias: "description"})
        ]);

    readonly similarity = new ModelList("list", [
            use(this.tcrdid, {alias: "tcrdid"}),
            use(this.targetDevelopmentLevel, {alias: "tdl"}),
            use(this.idgFamily, {alias: "fam"}),
            use(this.nameField),
            use(this.uniprot, {alias: "uniprot"}),
            use(this.preferredSymbol, {alias: "preferredSymbol"}),
            use(this.symbol, {alias: "sym"}),
            use(this.sequence, {alias: "seq"}),
            use(this.novelty, {alias: "novelty"})
        ], {name: "Similarity"});

    readonly overlap = new ModelList("overlap", [
            use(this.goProcess, {default: false}),
            use(this.jaxMgiPhenotype, {default: false}),
            use(this.goFunction, {default: false}),
            use(this.gwas, {default: false}),
            use(this.reactomePathway, {default: false}),
            use(this.wikipathwaysPathway, {default: false}),
            use(this.keggPathway, {default: false}),
            use(this.interactingViralProtein, {default: false}),
            use(this.interactingVirus, {default: false}),
            use(this.uniprotPathway, {default: false}),
            use(this.pathwaycommonsPathway, {default: false}),
            use(this.drug, {default: false}),
            use(this.pantherClass, {default: false}),
            use(this.dtoClass, {default: false}),
            use(this.associatedDiseaseField, {default: false}),
            use(this.uniprotKeyword, {default: false}),
            use(this.impcPhenotype, {default: false}),
            use(this.goComponent, {default: false})
        ]);

    readonly search = new ModelList("search", [
            use(this.symbol),
            use(this.uniprot),
            use(this.nameField),
            use(this.enspId),
            use(this.proteinAlias),
            use(this.ensemblId),
            use(this.uniprotFunction),
            use(this.ncbiGeneSummary)
        ]);

    readonly downloads = {
        singleValueFields: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.nameField),
            use(this.targetDevelopmentLevel),
            use(this.idgFamily),
            use(this.novelty),
            use(this.externalFamily, {default: false}),
            use(this.pdbIds, {default: false}),
            use(this.ncbiGeneSummary, {default: false}),
            use(this.antibodyCount, {default: false}),
            use(this.pubmedScore, {default: false}),
            use(this.pubtatorScore, {default: false}),
            use(this.uniprotFunction, {default: false})
        ], {name: "Single Value Fields"}),
        uniprotKeywords: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.uniprotKeyword),
            use(this.uniprotKeywordId)
        ], {name: "UniProt Keywords"}),
        interactingTargets: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.ppiDataSource2),
            use(this.stringdbInteractionScore),
            use(this.bioplexInteractionProbability),
            use(this.bioplexPNi),
            use(this.bioplexPWrong),
            use(this.ppiUniprot),
            use(this.ppiSymbol)
        ], {name: "Interacting Targets"}),
        associatedDiseases: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.diseaseDataSource),
            use(this.gardRare),
            use(this.jensenlabTextminingZscore),
            use(this.jensenlabConfidence),
            use(this.expressionAtlasLog2FoldChange),
            use(this.disgenetScore),
            use(this.associatedDiseaseEvidence),
            use(this.associatedDiseaseDrugName),
            use(this.associatedDiseasePValue),
            use(this.associatedDiseaseSource),
            use(this.associatedDiseaseSourceId),
            use(this.monarchS2o),
            use(this.linkedDisease),
            use(this.mondoId)
        ], {name: "Associated Diseases"}),
        pantherClasses: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.pantherClass),
            use(this.pantherClassId)
        ], {name: "PANTHER Classes"}),
        dtoClasses: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.dtoClass),
            use(this.dtoId),
            use(this.dtoDefinition)
        ], {name: "DTO Classes"}),
        sequence: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.sequence)
        ], {name: "Sequence"}),
        sequenceSearchResults: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.sequenceId),
            use(this.percentIdentical),
            use(this.alignmentLength),
            use(this.mismatchCount),
            use(this.gapCount),
            use(this.querySequenceStart),
            use(this.querySequenceEnd),
            use(this.subjectSequenceStart),
            use(this.subjectSequenceEnd),
            use(this.expectValue),
            use(this.bitScore),
            use(this.queryAlignment),
            use(this.subjectAlignment)
        ], {name: "Sequence Search Results"}),
        pubmedScores: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.pubmedScore2),
            use(this.pubmedScoreYear)
        ], {name: "PubMed Scores"}),
        pathways: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.pathwayType),
            use(this.pathwayName),
            use(this.pathwayUrl),
            use(this.pathwaySourceId)
        ], {name: "Pathways"}),
        drugsAndLigands: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.ligandName),
            use(this.ligandIsDrug),
            use(this.ligandSmiles),
            use(this.ligandPubchemId),
            use(this.ligandChemblId),
            use(this.ligandGuideToPharmacologyId),
            use(this.ligandDrugcentralId),
            use(this.ligandDescription),
            use(this.ligandActivity),
            use(this.ligandActivityType),
            use(this.ligandAction),
            use(this.ligandReferences),
            use(this.ligandReferenceSource),
            use(this.ligandPubmedIds),
            use(this.preferredTerm),
            use(this.unii)
        ], {name: "Drugs and Ligands"}),
        goTerms: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.goTermType),
            use(this.goTerm),
            use(this.goTermGoId),
            use(this.goTermEvidence),
            use(this.goTermAssignedBy)
        ], {name: "GO Terms"}),
        nearestTclinTargets: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.nearestTclinDirection),
            use(this.nearestTclinDistance),
            use(this.nearestTclinSymbol),
            use(this.nearestTclinUniprot)
        ], {name: "Nearest Tclin Targets"}),
        expression: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.expressionSource),
            use(this.expressionTissue),
            use(this.expressionQualitativeValue),
            use(this.expressionNumericValue),
            use(this.expressionSourceRank),
            use(this.expressionEvidence),
            use(this.expressionJensenlabOid),
            use(this.expressionUberonId),
            use(this.expressionSoureId)
        ], {name: "Expression"}),
        pubtatorScores: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.pubtatorScore2),
            use(this.pubtatorScoreYear)
        ], {name: "PubTator Scores"}),
        patentCounts: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.patentCount),
            use(this.patentCountYear)
        ], {name: "Patent Counts"}),
        tinxDiseaseAssociations: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.tinxTargetImportance),
            use(this.tinxDisease),
            use(this.tinxDiseaseSummary),
            use(this.tinxDiseaseDoid),
            use(this.tinxDiseaseNovelty)
        ], {name: "TINX Disease Associations"}),
        harmonizome: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.harmonizomeField),
            use(this.harmonizomeAttributeCount),
            use(this.harmonizomeAttributeCdf)
        ], {name: "Harmonizome"}),
        phenotype: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.phenotypeDataSource),
            use(this.trait),
            use(this.topLevelTermId),
            use(this.topLevelTermName),
            use(this.termId),
            use(this.termName),
            use(this.pValue),
            use(this.percentageChange),
            use(this.effectSize),
            use(this.procedureName),
            use(this.parameterName),
            use(this.gpAssoc),
            use(this.statisticalMethod),
            use(this.sex)
        ], {name: "Phenotype"}),
        gtex: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.gtexTissue),
            use(this.tpm),
            use(this.tpmMale),
            use(this.tpmFemale),
            use(this.tpmRank),
            use(this.tpmRankMale),
            use(this.tpmRankFemale),
            use(this.uberonId)
        ], {name: "GTEx"}),
        geneRifs: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.geneRifText),
            use(this.geneRifDate),
            use(this.geneRifPubmedIds),
            use(this.ncbiGeneId, {default: false})
        ], {name: "Gene RIFs"}),
        publications: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.pmid),
            use(this.title),
            use(this.journal),
            use(this.date),
            use(this.authors),
            use(this.source),
            use(this.abstract, {default: false})
        ], {name: "Publications"}),
        gwasAnalyticsTiga: new ModelList("download", [
            use(this.uniprot),
            use(this.symbol),
            use(this.tigaEnsgId),
            use(this.efoId),
            use(this.gwasTrait),
            use(this.studyCount),
            use(this.snpCount),
            use(this.weightedSnpCount),
            use(this.traitCountForGene),
            use(this.studyCountForGene),
            use(this.geneCountForTrait),
            use(this.studyCountForTrait),
            use(this.medianPValue),
            use(this.medianOddsRatio),
            use(this.betaCount),
            use(this.meanStudyN),
            use(this.rcras),
            use(this.meanRank),
            use(this.meanRankScore),
            use(this.tigaDiseaseLink, {default: false})
        ], {name: "GWAS Analytics (TIGA)"})
    };

    readonly associatedTarget = {
        facets: new ModelList("facet", [
            use(this.stringdbInteractionScore),
            use(this.bioplexInteractionProbability),
            use(this.ppiDataSource),
            use(this.targetDevelopmentLevel),
            use(this.idgFamily),
            use(this.nihTargetLists),
            use(this.reactomePathway),
            use(this.goProcess),
            use(this.goComponent),
            use(this.pantherClass),
            use(this.dtoClass),
            use(this.goFunction),
            use(this.ortholog),
            use(this.associatedDiseaseField),
            use(this.uniprotKeyword, {default: false}),
            use(this.impcPhenotype, {default: false}),
            use(this.jaxMgiPhenotype, {default: false}),
            use(this.gwas, {default: false}),
            use(this.expression, {default: false}),
            use(this.wikipathwaysPathway, {default: false}),
            use(this.keggPathway, {default: false}),
            use(this.interactingViralProtein, {default: false}),
            use(this.interactingVirus, {default: false}),
            use(this.logNovelty, {default: false}),
            use(this.logPubmedScore, {default: false}),
            use(this.dataSource, {default: false}),
            use(this.uniprotPathway, {default: false}),
            use(this.pathwaycommonsPathway, {default: false})
        ], {associatedModel: "Target"}),
        list: new ModelList("list", [
            use(this.tcrdid, {alias: "tcrdid"}),
            use(this.targetDevelopmentLevel, {alias: "tdl"}),
            use(this.idgFamily, {alias: "fam"}),
            use(this.nameField),
            use(this.uniprot, {alias: "uniprot"}),
            use(this.preferredSymbol, {alias: "preferredSymbol"}),
            use(this.symbol, {alias: "sym"}),
            use(this.sequence, {alias: "seq"}),
            use(this.novelty, {alias: "novelty"}),
            use(this.ncbiGeneSummary, {alias: "description"}),
            use(this.ppiDataSource2, {alias: "ppitypes"}),
            use(this.stringdbInteractionScore, {alias: "score"}),
            use(this.bioplexPNi, {alias: "p_ni"}),
            use(this.bioplexInteractionProbability, {alias: "p_int"}),
            use(this.bioplexPWrong, {alias: "p_wrong"})
        ], {associatedModel: "Target"})
    };

    readonly associatedDisease = {
        facets: new ModelList("facet", [
            use(this.jensenlabConfidence),
            use(this.expressionAtlasLog2FoldChange),
            use(this.disgenetScore),
            use(this.diseaseDataSource),
            use(this.linkedDisease),
            use(this.targetDevelopmentLevel),
            use(this.idgFamily),
            use(this.nihTargetLists),
            use(this.reactomePathway),
            use(this.pantherClass),
            use(this.dtoClass),
            use(this.goProcess),
            use(this.goComponent),
            use(this.goFunction),
            use(this.associatedDiseaseField),
            use(this.ortholog),
            use(this.uniprotKeyword, {default: false}),
            use(this.impcPhenotype, {default: false}),
            use(this.jaxMgiPhenotype, {default: false}),
            use(this.gwas, {default: false}),
            use(this.expression, {default: false}),
            use(this.wikipathwaysPathway, {default: false}),
            use(this.keggPathway, {default: false}),
            use(this.interactingViralProtein, {default: false}),
            use(this.interactingVirus, {default: false}),
            use(this.logNovelty, {default: false}),
            use(this.logPubmedScore, {default: false}),
            use(this.jensenlabTextminingZscore, {default: false}),
            use(this.dataSource, {default: false}),
            use(this.uniprotPathway, {default: false}),
            use(this.pathwaycommonsPathway, {default: false})
        ], {associatedModel: "Disease"}),
        list: new ModelList("list", [
            use(this.tcrdid, {alias: "tcrdid"}),
            use(this.targetDevelopmentLevel, {alias: "tdl"}),
            use(this.idgFamily, {alias: "fam"}),
            use(this.nameField),
            use(this.uniprot, {alias: "uniprot"}),
            use(this.preferredSymbol, {alias: "preferredSymbol"}),
            use(this.symbol, {alias: "sym"}),
            use(this.sequence, {alias: "seq"}),
            use(this.novelty, {alias: "novelty"}),
            use(this.diseaseSourceCount, {alias: "datasource_count"})
        ], {associatedModel: "Disease"})
    };

    readonly associatedLigand = {
        facets: new ModelList("facet", [
            use(this.predictedActivity),
            use(this.predictionApplicability),
            use(this.action),
            use(this.potency),
            use(this.activity),
            use(this.pantherClass),
            use(this.dtoClass),
            use(this.targetDevelopmentLevel),
            use(this.idgFamily),
            use(this.associatedDiseaseField),
            use(this.nihTargetLists),
            use(this.reactomePathway),
            use(this.goProcess),
            use(this.goComponent),
            use(this.goFunction),
            use(this.expression, {default: false}),
            use(this.wikipathwaysPathway, {default: false}),
            use(this.keggPathway, {default: false}),
            use(this.interactingViralProtein, {default: false}),
            use(this.interactingVirus, {default: false}),
            use(this.logNovelty, {default: false}),
            use(this.logPubmedScore, {default: false}),
            use(this.dataSource, {default: false}),
            use(this.uniprotPathway, {default: false}),
            use(this.pathwaycommonsPathway, {default: false}),
            use(this.uniprotKeyword, {default: false}),
            use(this.ortholog, {default: false}),
            use(this.impcPhenotype, {default: false}),
            use(this.jaxMgiPhenotype, {default: false}),
            use(this.gwas, {default: false})
        ], {associatedModel: "Ligand"}),
        list: new ModelList("list", [
            use(this.tcrdid, {alias: "tcrdid"}),
            use(this.targetDevelopmentLevel, {alias: "tdl"}),
            use(this.idgFamily, {alias: "fam"}),
            use(this.nameField),
            use(this.uniprot, {alias: "uniprot"}),
            use(this.preferredSymbol, {alias: "preferredSymbol"}),
            use(this.symbol, {alias: "sym"}),
            use(this.sequence, {alias: "seq"}),
            use(this.novelty, {alias: "novelty"}),
            use(this.activityValues, {alias: "actVals"}),
            use(this.averageActivityValue, {alias: "avgActVal"}),
            use(this.ligandActions, {alias: "modeOfAction"}),
            use(this.predictionApplicability, {alias: "similarity"}),
            use(this.predictedActivity, {alias: "result"}),
            use(this.predictionTrainingSmiles, {alias: "training_smiles"}),
            use(this.predictionTrainingActivity, {alias: "training_activity"}),
            use(this.predictionModelName, {alias: "model_name"}),
            use(this.predictionTargetChemblId, {alias: "target_chembl_id"})
        ], {associatedModel: "Ligand"}),
        singleValueFields: new ModelList("download", [
            use(this.activityValues),
            use(this.averageActivityValue),
            use(this.ligandActions),
            use(this.predictionApplicability),
            use(this.predictedActivity),
            use(this.predictionTrainingSmiles),
            use(this.predictionTrainingActivity),
            use(this.predictionModelName),
            use(this.predictionTargetChemblId)
        ], {name: "Single Value Fields", associatedModel: "Ligand"})
    };

}

export const targetModelConfig = new TargetModelConfig();
