import { parsePythonJSON } from "./PythonCalculation";

const axios = require('axios');
const crypto = require('crypto');

export class ModelDetails {
    AUC: number;
    'Applicability domain': string;
    'Balanced Accuracy': number;
    Descriptors: string;
    'End Point': string;
    Group: string;
    Link: string;
    'Machine learning approach': string;
    Model_ID: string;
    Name: string;
    'Number compounds in the test set': number;
    'Number compounds in the training set': number;
    'Prediction Type': string;
    R2: number;
    RMSE: number
    Reference: string;
    Source: string;
    Title: string;
    'Validation approach': string

}

export class PredictorResult {
    applicability: number;
    model: ModelDetails;
    nearest: { result:number, smiles: string };
    result: number
}


export class DrugTargetPrediction {
    smiles: string;
    similarityCutoff: number = 0.5;
    knex: any;
    queryHash: string;
    modelMap: Map<string, number> = new Map<string, number>();

    constructor(knex: any, smiles: string) {
        this.knex = knex;
        this.smiles = smiles;
        this.queryHash = this.getQueryHash();
        this.initMap();
    }

    async getPredictedTargets() {
        if (!this.smiles) {
            return [];
        }
        const existingQuery = await this.getQueryCount();
        if (existingQuery.length > 0 && existingQuery[0].count > 0) {
            switch (existingQuery[0].query_status) {
                case 'success':
                    return this.updateQueryCount(existingQuery[0].count);
                case 'in progress':
                    throw new Error('this query is still in progress');
                case 'fail':
                    throw new Error(existingQuery[0].error);
            }
        } else {
            return Promise.all([
                axios.get(this.url()),
                this.startNewQuery()
            ])
                .then((response: any) => {
                    return Promise.all([
                        this.addResults(response[0].data),
                        this.updateQueryStatus('success', '')
                    ])
                })
                .catch((error: any) => {
                    return this.updateQueryStatus('fail', JSON.stringify(error));
                });
        }
    }

    private addResults(dataBlob: string) {
        let filteredData: PredictorResult[] = parsePythonJSON(dataBlob);
        const inserts: any[] = [];
        filteredData.forEach((row: PredictorResult) => {

            const modelstring = row.model.Name.split(row.model["End Point"])[0];
            const models = modelstring.split('|') || [modelstring];
            models.forEach((model: string) => {
                const protein_id = this.modelMap.get(model.trim());
                if(protein_id && !inserts.find(ex => ex.protein_id === protein_id)) {
                    inserts.push({
                        id: null,
                        query_hash: this.queryHash,
                        protein_id: protein_id,
                        result: row.result,
                        end_point: row.model["End Point"],
                        neighbor_smiles: row.nearest.smiles,
                        neighbor_activity: row.nearest.result,
                        neighbor_unit: "pIC50",
                        similarity: row.applicability,
                        model_name: row.model.Name,
                        model_type: row.model["Prediction Type"],
                        target_chembl_id: row.model.Model_ID,
                        group: row.model.Group
                    });
                }
            });
        });

        const queries = [];
        while (inserts.length > 0) {
            queries.push(this.knex('result_cache.predictor_results').insert(inserts.splice(0, 25000)));
        }
        return Promise.all(queries);
    }

    private updateQueryStatus(status: string, error: string) {
        const q = this.knex('result_cache.search_query').update(
            {
                query_status: status,
                error: error
            }).where('query_hash', this.queryHash);
        return q;
    }

    private startNewQuery() {
        const date = new Date().toISOString();
        return this.knex('result_cache.search_query')
            .insert({
                query_hash: this.queryHash,
                query: this.url(),
                query_status: 'in progress',
                count: 1,
                first_query: date,
                last_query: date
            })
    }

    private updateQueryCount(currentCount: number) {
        return this.knex('result_cache.search_query')
            .where('query_hash', this.queryHash)
            .update({
                count: currentCount + 1,
                last_query: new Date().toISOString()
            });
    }

    private getQueryCount() {
        return this.knex('result_cache.search_query')
            .select(['count', 'query_status', 'error'])
            .where('query_hash', this.queryHash);
    }

    private getQueryHash() {
        return crypto.createHash('sha1').update(this.url()).digest('base64').substring(0, 20);
    }

    private url(): string {
        return 'https://stitcher.ncats.io/predictor/predictedTargets?smiles=' + encodeURIComponent(this.smiles);
    }

    initMap(){
        this.modelMap.set('Cytochrome P450 26A1',51);
        this.modelMap.set('Cytochrome P450 1A2',53);
        this.modelMap.set('Cytochrome P450 1B1',56);
        this.modelMap.set('Cytochrome P450 2D6',58);
        this.modelMap.set('C-X-C chemokine receptor type 2',115);
        this.modelMap.set('C-X-C chemokine receptor type 4',117);
        this.modelMap.set('Cytochrome P450 2C8',125);
        this.modelMap.set('Cytochrome P450 2J2',126);
        this.modelMap.set('C-X-C chemokine receptor type 5',155);
        this.modelMap.set('Cytochrome b-245 heavy chain',162);
        this.modelMap.set('Ceramide glucosyltransferase',173);
        this.modelMap.set('Cannabinoid receptor 1',207);
        this.modelMap.set('Complement C3',216);
        this.modelMap.set('1,25-dihydroxyvitamin D(3) 24-hydroxylase, mitochondrial',231);
        this.modelMap.set('C-X-C chemokine receptor type 3',272);
        this.modelMap.set('Cytochrome P450 2C19',284);
        this.modelMap.set('Cytochrome P450 2A6',285);
        this.modelMap.set('Chymotrypsin-C',312);
        this.modelMap.set('C-X-C chemokine receptor type 1',333);
        this.modelMap.set('Cyclin-dependent kinase 1',336);
        this.modelMap.set('Cholesteryl ester transfer protein',356);
        this.modelMap.set('Cannabinoid receptor 2',382);
        this.modelMap.set('Carnitine O-palmitoyltransferase 1, liver isoform',410);
        this.modelMap.set('Tyrosine-protein kinase CSK',426);
        this.modelMap.set('C-C chemokine receptor type 9',473);
        this.modelMap.set('DNA (cytosine-5)-methyltransferase 3B',492);
        this.modelMap.set('DNA (cytosine-5)-methyltransferase 1',495);
        this.modelMap.set('CCR4-NOT transcription complex subunit 7',533);
        this.modelMap.set('D(1A) dopamine receptor',569);
        this.modelMap.set('D(2) dopamine receptor',570);
        this.modelMap.set('D(4) dopamine receptor',572);
        this.modelMap.set('Cytochrome P450 3A4',574);
        this.modelMap.set('Cytochrome P450 2B6',577);
        this.modelMap.set('Ephrin type-B receptor 3',589);
        this.modelMap.set('N-arachidonyl glycine receptor',609);
        this.modelMap.set('Cyclin-dependent kinase 7',663);
        this.modelMap.set('Cystic fibrosis transmembrane conductance regulator',678);
        this.modelMap.set('Dipeptidyl peptidase 2',694);
        this.modelMap.set('Dipeptidyl peptidase 4',696);
        this.modelMap.set('Dipeptidyl peptidase 8',699);
        this.modelMap.set('Dipeptidyl peptidase 9',700);
        this.modelMap.set('Histone acetyltransferase p300',712);
        this.modelMap.set('Ephrin type-A receptor 2',717);
        this.modelMap.set('DNA repair protein complementing XP-G cells',723);
        this.modelMap.set('Squalene monooxygenase',727);
        this.modelMap.set('Lanosterol synthase',731);
        this.modelMap.set('Serine/threonine-protein kinase/endoribonuclease IRE1',735);
        this.modelMap.set('Steroid hormone receptor ERR1',754);
        this.modelMap.set('Estrogen receptor',767);
        this.modelMap.set('Growth factor receptor-bound protein 2',781);
        this.modelMap.set('Egl nine homolog 1',784);
        this.modelMap.set('Ephrin type-B receptor 4',798);
        this.modelMap.set('G-protein coupled receptor 35',813);
        this.modelMap.set('G-protein coupled receptor 55',818);
        this.modelMap.set('G-protein coupled receptor 6',822);
        this.modelMap.set('Gamma-aminobutyric acid receptor subunit rho-1',845);
        this.modelMap.set('Geranylgeranyl pyrophosphate synthase',865);
        this.modelMap.set('Gastric inhibitory polypeptide receptor',899);
        this.modelMap.set('Endoplasmin',909);
        this.modelMap.set('Endoplasmic reticulum aminopeptidase 1',920);
        this.modelMap.set('Ectonucleotide pyrophosphatase/phosphodiesterase family member 2',979);
        this.modelMap.set('Receptor tyrosine-protein kinase erbB-2',989);
        this.modelMap.set('Sorbitol dehydrogenase',996);
        this.modelMap.set('Deoxyuridine 5\'-triphosphate nucleotidohydrolase, mitochondrial',1005);
        this.modelMap.set('Gamma-aminobutyric acid receptor subunit alpha-1',1031);
        this.modelMap.set('Dual specificity protein phosphatase 3',1062);
        this.modelMap.set('Histone-lysine N-methyltransferase EHMT2',1068);
        this.modelMap.set('Neutrophil elastase',1079);
        this.modelMap.set('Dynamin-2',1103);
        this.modelMap.set('Dual specificity tyrosine-phosphorylation-regulated kinase 1B',1104);
        this.modelMap.set('Dual specificity tyrosine-phosphorylation-regulated kinase 2',1107);
        this.modelMap.set('Eukaryotic translation initiation factor 2-alpha kinase 1',1113);
        this.modelMap.set('Interferon-induced, double-stranded RNA-activated protein kinase',1114);
        this.modelMap.set('Eukaryotic translation initiation factor 2-alpha kinase 3',1117);
        this.modelMap.set('Dihydrofolate reductase',1137);
        this.modelMap.set('Excitatory amino acid transporter 3',1149);
        this.modelMap.set('Glucokinase regulatory protein',1176);
        this.modelMap.set('Glucocorticoid receptor',1184);
        this.modelMap.set('Endothelin-converting enzyme 1',1201);
        this.modelMap.set('Dopamine beta-hydroxylase',1252);
        this.modelMap.set('DNA polymerase alpha catalytic subunit',1278);
        this.modelMap.set('Gamma-aminobutyric acid receptor subunit gamma-2',1283);
        this.modelMap.set('Dual specificity tyrosine-phosphorylation-regulated kinase 1A',1303);
        this.modelMap.set('Deoxycytidine kinase',1337);
        this.modelMap.set('Discoidin domain-containing receptor 2',1342);
        this.modelMap.set('Testosterone 17-beta-dehydrogenase 3',1354);
        this.modelMap.set('Egl nine homolog 3',1383);
        this.modelMap.set('Ectonucleotide pyrophosphatase/phosphodiesterase family member 1',1386);
        this.modelMap.set('6-phosphofructo-2-kinase/fructose-2,6-bisphosphatase 2',1440);
        this.modelMap.set('Coagulation factor XI',1456);
        this.modelMap.set('Coagulation factor X',1457);
        this.modelMap.set('Egl nine homolog 2',1472);
        this.modelMap.set('Endoplasmic reticulum aminopeptidase 2',1479);
        this.modelMap.set('Coagulation factor XIII A chain',1497);
        this.modelMap.set('6-phosphofructo-2-kinase/fructose-2,6-bisphosphatase 1',1547);
        this.modelMap.set('Elongation of very long chain fatty acids protein 6',1555);
        this.modelMap.set('Histone-lysine N-methyltransferase EZH2',1623);
        this.modelMap.set('Epidermal growth factor receptor',1639);
        this.modelMap.set('Histone-lysine N-methyltransferase EHMT1',1642);
        this.modelMap.set('Estrogen receptor beta',1652);
        this.modelMap.set('Liver carboxylesterase 1',1657);
        this.modelMap.set('Cocaine esterase',1658);
        this.modelMap.set('Coagulation factor XII',1680);
        this.modelMap.set('Fructose-1,6-bisphosphatase 1',1700);
        this.modelMap.set('6-phosphofructo-2-kinase/fructose-2,6-bisphosphatase 3',1729);
        this.modelMap.set('6-phosphofructo-2-kinase/fructose-2,6-bisphosphatase 4',1730);
        this.modelMap.set('Focal adhesion kinase 1',1760);
        this.modelMap.set('ADP-ribosyl cyclase/cyclic ADP-ribose hydrolase 1',1853);
        this.modelMap.set('DNA ligase 1',1894);
        this.modelMap.set('Chymotrypsinogen B',1944);
        this.modelMap.set('Carnitine O-palmitoyltransferase 1, muscle isoform',1953);
        this.modelMap.set('Corticotropin-releasing factor receptor 2',1958);
        this.modelMap.set('Macrophage colony-stimulating factor 1 receptor',1969);
        this.modelMap.set('Casein kinase II subunit alpha\'',1971);
        this.modelMap.set('Lanosterol 14-alpha demethylase',1985);
        this.modelMap.set('Carboxy-terminal domain RNA polymerase II polypeptide A small phosphatase 1',2052);
        this.modelMap.set('Catenin beta-1',2058);
        this.modelMap.set('Coagulation factor VII',2087);
        this.modelMap.set('Malonyl-CoA decarboxylase, mitochondrial',2113);
        this.modelMap.set('Cytochrome P450 26B1',2115);
        this.modelMap.set('Carbonic anhydrase 5A, mitochondrial',2135);
        this.modelMap.set('Caspase-9',2144);
        this.modelMap.set('CREB-binding protein',2167);
        this.modelMap.set('G1/S-specific cyclin-E1',2173);
        this.modelMap.set('G2/mitotic-specific cyclin-B1',2174);
        this.modelMap.set('C-C chemokine receptor type 2',2179);
        this.modelMap.set('Cytidine deaminase',2198);
        this.modelMap.set('Cyclin-dependent kinase 9',2201);
        this.modelMap.set('Bromodomain-containing protein 4',2215);
        this.modelMap.set('Voltage-dependent T-type calcium channel subunit alpha-1H',2223);
        this.modelMap.set('Caspase-7',2229);
        this.modelMap.set('Cathepsin L1',2232);
        this.modelMap.set('Cathepsin S',2233);
        this.modelMap.set('Cathepsin L2',2234);
        this.modelMap.set('Carboxypeptidase B2',2243);
        this.modelMap.set('Cholecystokinin receptor type A',2262);
        this.modelMap.set('G2/mitotic-specific cyclin-B2',2265);
        this.modelMap.set('Cathepsin G',2288);
        this.modelMap.set('Carbonyl reductase [NADPH] 1',2304);
        this.modelMap.set('C-C chemokine receptor type 4',2316);
        this.modelMap.set('C-C chemokine receptor type 3',2320);
        this.modelMap.set('Cathepsin E',2332);
        this.modelMap.set('Cathepsin K',2338);
        this.modelMap.set('G1/S-specific cyclin-E2',2364);
        this.modelMap.set('Cell division control protein 42 homolog',2377);
        this.modelMap.set('Cyclin-dependent kinase 4',2380);
        this.modelMap.set('Caspase-2',2385);
        this.modelMap.set('Caspase-8',2386);
        this.modelMap.set('Pro-cathepsin H',2394);
        this.modelMap.set('C-C chemokine receptor type 6',2417);
        this.modelMap.set('C-C chemokine receptor-like 2',2421);
        this.modelMap.set('C-C chemokine receptor type 5',2424);
        this.modelMap.set('Dipeptidyl peptidase 1',2442);
        this.modelMap.set('Cyclin-A2',2460);
        this.modelMap.set('Cyclin-T1',2485);
        this.modelMap.set('C-C chemokine receptor type 1',2488);
        this.modelMap.set('C-C chemokine receptor type 8',2489);
        this.modelMap.set('G1/S-specific cyclin-D1',2540);
        this.modelMap.set('B-cell receptor CD22',2541);
        this.modelMap.set('Cyclin-dependent kinase 5 activator 1',2546);
        this.modelMap.set('Estradiol 17-beta-dehydrogenase 1',2615);
        this.modelMap.set('Corticosteroid 11-beta-dehydrogenase isozyme 2',2660);
        this.modelMap.set('Dihydropteridine reductase',2661);
        this.modelMap.set('Diacylglycerol O-acyltransferase 1',2696);
        this.modelMap.set('Sn1-specific diacylglycerol lipase alpha',2699);
        this.modelMap.set('Peptide deformylase, mitochondrial',2705);
        this.modelMap.set('Corticosteroid 11-beta-dehydrogenase isozyme 1',2737);
        this.modelMap.set('Non-lysosomal glucosylceramidase',2768);
        this.modelMap.set('Gamma-aminobutyric acid receptor subunit beta-2',2778);
        this.modelMap.set('Complement factor D',2784);
        this.modelMap.set('Cytochrome P450 2C9',2811);
        this.modelMap.set('Complement factor B',2955);
        this.modelMap.set('Cell division cycle 7-related protein kinase',2973);
        this.modelMap.set('Cyclin-dependent kinase 2',2996);
        this.modelMap.set('Cyclin-dependent kinase inhibitor 1',2998);
        this.modelMap.set('Cyclin-dependent-like kinase 5',3000);
        this.modelMap.set('Carnitine O-palmitoyltransferase 2, mitochondrial',3038);
        this.modelMap.set('Cytochrome P450 2E1',3066);
        this.modelMap.set('Corticotropin-releasing factor receptor 1',3074);
        this.modelMap.set('Casein kinase II subunit alpha',3082);
        this.modelMap.set('Cytochrome P450 3A5',3096);
        this.modelMap.set('Protein DBF4 homolog A',3135);
        this.modelMap.set('Estradiol 17-beta-dehydrogenase 2',3148);
        this.modelMap.set('S-adenosylmethionine decarboxylase proenzyme',3181);
        this.modelMap.set('Death-associated protein kinase 1',3273);
        this.modelMap.set('Excitatory amino acid transporter 1',3295);
        this.modelMap.set('Excitatory amino acid transporter 2',3297);
        this.modelMap.set('Dihydroorotate dehydrogenase (quinone), mitochondrial',3349);
        this.modelMap.set('Glycogen phosphorylase, muscle form',3361);
        this.modelMap.set('Tyrosine-protein phosphatase non-receptor type 2',3384);
        this.modelMap.set('Tyrosine-protein phosphatase non-receptor type 11',3385);
        this.modelMap.set('Tyrosine-protein phosphatase non-receptor type 7',3386);
        this.modelMap.set('Receptor-type tyrosine-protein phosphatase F',3391);
        this.modelMap.set('DNA repair protein RAD51 homolog 1',3403);
        this.modelMap.set('RAF proto-oncogene serine/threonine-protein kinase',3405);
        this.modelMap.set('Proto-oncogene tyrosine-protein kinase receptor Ret',3437);
        this.modelMap.set('Prolactin-releasing peptide receptor',3546);
        this.modelMap.set('Proteasome subunit beta type-9',3547);
        this.modelMap.set('Proteasome subunit beta type-5',3548);
        this.modelMap.set('Prostaglandin E synthase',3552);
        this.modelMap.set('Glutaminyl-peptide cyclotransferase',3564);
        this.modelMap.set('Proteasome subunit beta type-2',3565);
        this.modelMap.set('Orexin receptor type 1',3579);
        this.modelMap.set('D-aspartate oxidase',3588);
        this.modelMap.set('Cytosolic phospholipase A2',3589);
        this.modelMap.set('Cytosolic phospholipase A2 beta',3590);
        this.modelMap.set('Plasminogen activator inhibitor 1',3600);
        this.modelMap.set('Proteinase-activated receptor 4',3611);
        this.modelMap.set('Glycogen phosphorylase, liver form',3654);
        this.modelMap.set('Protein phosphatase 1A',3666);
        this.modelMap.set('DNA-dependent protein kinase catalytic subunit',3667);
        this.modelMap.set('Proteasome subunit beta type-6',3668);
        this.modelMap.set('1-phosphatidylinositol 4,5-bisphosphate phosphodiesterase gamma-1',3685);
        this.modelMap.set('Phospholipase D1',3707);
        this.modelMap.set('Phospholipase D2',3708);
        this.modelMap.set('Vitamin K-dependent protein C',3720);
        this.modelMap.set('Protein-tyrosine kinase 6',3748);
        this.modelMap.set('Tyrosine-protein phosphatase non-receptor type 9',3751);
        this.modelMap.set('Receptor-type tyrosine-protein phosphatase beta',3752);
        this.modelMap.set('Receptor-type tyrosine-protein phosphatase gamma',3754);
        this.modelMap.set('Receptor-type tyrosine-protein phosphatase S',3758);
        this.modelMap.set('Proteasome subunit alpha type-1',3781);
        this.modelMap.set('Proteasome subunit beta type-1',3801);
        this.modelMap.set('Proteasome subunit beta type-8',3803);
        this.modelMap.set('Myeloblastin',3812);
        this.modelMap.set('Proteasome subunit alpha type-5',3813);
        this.modelMap.set('Proteasome subunit alpha type-3',3814);
        this.modelMap.set('Proteasome subunit alpha type-6',3815);
        this.modelMap.set('Proteasome subunit alpha type-4',3816);
        this.modelMap.set('Trifunctional purine biosynthetic protein adenosine-3',3820);
        this.modelMap.set('Proteasome subunit alpha type-2',3837);
        this.modelMap.set('Tyrosine-protein phosphatase non-receptor type 12',3863);
        this.modelMap.set('Tyrosine-protein phosphatase non-receptor type 13',3864);
        this.modelMap.set('Tyrosine-protein phosphatase non-receptor type 1',3867);
        this.modelMap.set('Tyrosine-protein phosphatase non-receptor type 5',3873);
        this.modelMap.set('Tyrosine-protein phosphatase non-receptor type 6',3874);
        this.modelMap.set('Receptor-type tyrosine-protein phosphatase alpha',3875);
        this.modelMap.set('26S proteasome non-ATPase regulatory subunit 14',3879);
        this.modelMap.set('Tyrosine-protein phosphatase non-receptor type 22',3880);
        this.modelMap.set('Receptor-type tyrosine-protein phosphatase C',3883);
        this.modelMap.set('Proteasome subunit alpha type-7',3929);
        this.modelMap.set('SUMO-activating enzyme subunit 1',4028);
        this.modelMap.set('3-oxo-5-alpha-steroid 4-dehydrogenase 1',4031);
        this.modelMap.set('Solute carrier family 22 member 2',4066);
        this.modelMap.set('Solute carrier family 22 member 6',4075);
        this.modelMap.set('Sodium/nucleoside cotransporter 2',4085);
        this.modelMap.set('SUMO-activating enzyme subunit 2',4089);
        this.modelMap.set('Sodium channel protein type 2 subunit alpha',4110);
        this.modelMap.set('Solute carrier family 22 member 12',4116);
        this.modelMap.set('Tubulin beta-1 chain',4178);
        this.modelMap.set('Solute carrier family 22 member 3',4197);
        this.modelMap.set('Sphingosine 1-phosphate receptor 5',4199);
        this.modelMap.set('Sodium- and chloride-dependent betaine transporter',4211);
        this.modelMap.set('Adenosylhomocysteinase',4214);
        this.modelMap.set('Solute carrier family 22 member 1',4226);
        this.modelMap.set('Sphingosine 1-phosphate receptor 2',4252);
        this.modelMap.set('Sphingosine 1-phosphate receptor 4',4254);
        this.modelMap.set('Sterol regulatory element-binding protein 2',4292);
        this.modelMap.set('Serine/threonine-protein kinase Sgk1',4341);
        this.modelMap.set('Proto-oncogene tyrosine-protein kinase Src',4422);
        this.modelMap.set('DNA-directed RNA polymerase I subunit RPA1',4438);
        this.modelMap.set('Rho-associated protein kinase 2',4439);
        this.modelMap.set('Nuclear receptor ROR-gamma',4516);
        this.modelMap.set('Macrophage-stimulating protein receptor',4534);
        this.modelMap.set('Solute carrier family 15 member 1',4570);
        this.modelMap.set('Equilibrative nucleoside transporter 1',4573);
        this.modelMap.set('Lysine--tRNA ligase',4604);
        this.modelMap.set('Nuclear receptor ROR-alpha',4764);
        this.modelMap.set('Rho-associated protein kinase 1',4788);
        this.modelMap.set('Nuclear receptor ROR-beta',4791);
        this.modelMap.set('Proto-oncogene tyrosine-protein kinase ROS',4793);
        this.modelMap.set('Rap guanine nucleotide exchange factor 4',4806);
        this.modelMap.set('Serine/threonine-protein kinase 17A',4827);
        this.modelMap.set('Signal transducer and activator of transcription 3',4843);
        this.modelMap.set('Somatostatin receptor type 1',4993);
        this.modelMap.set('Heat shock protein 75 kDa, mitochondrial',5002);
        this.modelMap.set('Suppressor of tumorigenicity 14 protein',5012);
        this.modelMap.set('Somatostatin receptor type 2',5055);
        this.modelMap.set('Somatostatin receptor type 3',5056);
        this.modelMap.set('Somatostatin receptor type 4',5057);
        this.modelMap.set('Somatostatin receptor type 5',5060);
        this.modelMap.set('Serine/threonine-protein kinase 17B',5092);
        this.modelMap.set('Sphingosine kinase 2',5108);
        this.modelMap.set('Signal transducer and activator of transcription 6',5161);
        this.modelMap.set('Ubiquitin carboxyl-terminal hydrolase 7',5233);
        this.modelMap.set('Methionine--tRNA ligase, cytoplasmic',5245);
        this.modelMap.set('Vitamin D3 receptor',5290);
        this.modelMap.set('Vasopressin V1a receptor',5334);
        this.modelMap.set('Vascular endothelial growth factor receptor 3',5362);
        this.modelMap.set('Tyrosine-protein kinase Yes',5367);
        this.modelMap.set('Thymidine phosphorylase',5427);
        this.modelMap.set('Tyrosine-protein kinase receptor TYRO3',5430);
        this.modelMap.set('Non-receptor tyrosine-protein kinase TYK2',5431);
        this.modelMap.set('Transient receptor potential cation channel subfamily V member 3',5442);
        this.modelMap.set('Thymidylate synthase',5444);
        this.modelMap.set('Interleukin-1 receptor-associated kinase 4',5482);
        this.modelMap.set('Histamine H4 receptor',5494);
        this.modelMap.set('Heat shock 70 kDa protein 1A',5496);
        this.modelMap.set('Heat shock protein HSP 90-alpha',5497);
        this.modelMap.set('Protein-S-isoprenylcysteine O-methyltransferase',5507);
        this.modelMap.set('Insulin-degrading enzyme',5518);
        this.modelMap.set('Bifunctional epoxide hydrolase 2',5550);
        this.modelMap.set('Integrin-linked protein kinase',5569);
        this.modelMap.set('Inhibitor of nuclear factor kappa-B kinase subunit epsilon',5589);
        this.modelMap.set('Inhibitor of nuclear factor kappa-B kinase subunit alpha',5592);
        this.modelMap.set('E3 ubiquitin-protein ligase Mdm2',5596);
        this.modelMap.set('Protein Mdm4',5597);
        this.modelMap.set('Multidrug resistance protein 1',5599);
        this.modelMap.set('Inhibitor of nuclear factor kappa-B kinase subunit beta',5713);
        this.modelMap.set('Proto-oncogene c-Fos',5724);
        this.modelMap.set('Free fatty acid receptor 2',5755);
        this.modelMap.set('Galanin receptor type 1',5807);
        this.modelMap.set('Farnesyl pyrophosphate synthase',5814);
        this.modelMap.set('Tissue alpha-L-fucosidase',5818);
        this.modelMap.set('Tyrosine-protein kinase Fyn',5845);
        this.modelMap.set('Fatty acid-binding protein, heart',5849);
        this.modelMap.set('fMet-Leu-Phe receptor',5873);
        this.modelMap.set('Ephrin type-B receptor 2',5891);
        this.modelMap.set('Fatty acid synthase',5908);
        this.modelMap.set('Free fatty acid receptor 1',5918);
        this.modelMap.set('Solute carrier family 2, facilitated glucose transporter member 3',5942);
        this.modelMap.set('Heparanase',5975);
        this.modelMap.set('Glutathione S-transferase P',5993);
        this.modelMap.set('G protein-activated inward rectifier potassium channel 2',5997);
        this.modelMap.set('Histamine H3 receptor',6022);
        this.modelMap.set('3-hydroxy-3-methylglutaryl-coenzyme A reductase',6025);
        this.modelMap.set('Heat shock protein HSP 90-beta',6078);
        this.modelMap.set('Heat shock cognate 71 kDa protein',6080);
        this.modelMap.set('Hematopoietic prostaglandin D synthase',6094);
        this.modelMap.set('Histamine H2 receptor',6097);
        this.modelMap.set('Hypoxia-inducible factor 1-alpha',6111);
        this.modelMap.set('Thymidine kinase, cytosolic',6115);
        this.modelMap.set('Hydroxycarboxylic acid receptor 2',6116);
        this.modelMap.set('Histone deacetylase 4',6151);
        this.modelMap.set('N-lysine methyltransferase KMT5A',6160);
        this.modelMap.set('Histone deacetylase 6',6166);
        this.modelMap.set('Histone deacetylase 1',6169);
        this.modelMap.set('HLA class II histocompatibility antigen gamma chain',6188);
        this.modelMap.set('KiSS-1 receptor',6230);
        this.modelMap.set('Histone deacetylase 7',6240);
        this.modelMap.set('Histone deacetylase 11',6242);
        this.modelMap.set('Histone deacetylase 9',6245);
        this.modelMap.set('Histone deacetylase 2',6248);
        this.modelMap.set('Serine protease hepsin',6253);
        this.modelMap.set('Protein farnesyltransferase subunit beta',6301);
        this.modelMap.set('Receptor-type tyrosine-protein kinase FLT3',6304);
        this.modelMap.set('Glyceraldehyde-3-phosphate dehydrogenase',6322);
        this.modelMap.set('Growth hormone secretagogue receptor type 1',6346);
        this.modelMap.set('Gastrin/cholecystokinin type B receptor',6354);
        this.modelMap.set('Glucose-6-phosphatase',6362);
        this.modelMap.set('Peptidyl-prolyl cis-trans isomerase FKBP1A',6380);
        this.modelMap.set('Fibroblast growth factor receptor 1',6463);
        this.modelMap.set('Peptidyl-prolyl cis-trans isomerase FKBP5',6467);
        this.modelMap.set('Fibroblast growth factor receptor 2',6489);
        this.modelMap.set('Fibroblast growth factor receptor 4',6492);
        this.modelMap.set('Peptidyl-prolyl cis-trans isomerase FKBP4',6495);
        this.modelMap.set('Protein farnesyltransferase/geranylgeranyltransferase type-1 subunit alpha',6501);
        this.modelMap.set('Fatty acid-binding protein, adipocyte',6505);
        this.modelMap.set('Flap endonuclease 1',6549);
        this.modelMap.set('Protein-tyrosine kinase 2-beta',6562);
        this.modelMap.set('Squalene synthase',6590);
        this.modelMap.set('Fatty-acid amide hydrolase 1',6597);
        this.modelMap.set('IgG receptor FcRn large subunit p51',6605);
        this.modelMap.set('Fibroblast growth factor receptor 3',6618);
        this.modelMap.set('Low affinity immunoglobulin epsilon Fc receptor',6646);
        this.modelMap.set('Tyrosine-protein kinase Fgr',6656);
        this.modelMap.set('Hexokinase-1',6683);
        this.modelMap.set('Epoxide hydrolase 1',6708);
        this.modelMap.set('Histamine H1 receptor',6721);
        this.modelMap.set('Eukaryotic translation initiation factor 4E',6849);
        this.modelMap.set('Homeodomain-interacting protein kinase 1',6864);
        this.modelMap.set('Integrin alpha-IIb',6885);
        this.modelMap.set('Integrin alpha-4',6886);
        this.modelMap.set('Integrin beta-5',6889);
        this.modelMap.set('Hepatocyte growth factor receptor',6933);
        this.modelMap.set('Casein kinase I isoform delta',6937);
        this.modelMap.set('Casein kinase I isoform gamma-2',6942);
        this.modelMap.set('Insulin-like growth factor 1 receptor',6956);
        this.modelMap.set('Maternal embryonic leucine zipper kinase',6967);
        this.modelMap.set('Integrin beta-2',6970);
        this.modelMap.set('Integrin beta-3',6971);
        this.modelMap.set('Tyrosine-protein kinase ITK/TSK',6974);
        this.modelMap.set('Integrin beta-7',6975);
        this.modelMap.set('Tyrosine-protein kinase JAK3',6994);
        this.modelMap.set('Histone acetyltransferase KAT2B',7011);
        this.modelMap.set('Tyrosine-protein kinase Mer',7070);
        this.modelMap.set('Transcription factor AP-1',7089);
        this.modelMap.set('Tissue-type plasminogen activator',7562);
        this.modelMap.set('Translocator protein',7585);
        this.modelMap.set('Transient receptor potential cation channel subfamily V member 1',7612);
        this.modelMap.set('Toll-like receptor 2',7643);
        this.modelMap.set('Tryptophan 5-hydroxylase 1',7665);
        this.modelMap.set('Thiopurine S-methyltransferase',7688);
        this.modelMap.set('Protein tyrosine phosphatase type IVA 3',7695);
        this.modelMap.set('Tryptase alpha/beta-1',7699);
        this.modelMap.set('Troponin C, slow skeletal and cardiac muscles',7721);
        this.modelMap.set('Tumor necrosis factor',7777);
        this.modelMap.set('Tankyrase-1',7797);
        this.modelMap.set('Lymphokine-activated killer T-cell-originated protein kinase',7801);
        this.modelMap.set('Sodium/hydrogen exchanger 1',7827);
        this.modelMap.set('TRAF2 and NCK-interacting protein kinase',7853);
        this.modelMap.set('Sphingosine kinase 1',7855);
        this.modelMap.set('NAD-dependent protein deacetylase sirtuin-3, mitochondrial',7878);
        this.modelMap.set('NAD-dependent protein deacetylase sirtuin-2',7885);
        this.modelMap.set('Solute carrier organic anion transporter family member 1B1',7969);
        this.modelMap.set('Sterol O-acyltransferase 2',7978);
        this.modelMap.set('Smoothened homolog',8087);
        this.modelMap.set('Solute carrier organic anion transporter family member 1B3',8095);
        this.modelMap.set('N-lysine methyltransferase SMYD2',8128);
        this.modelMap.set('Sentrin-specific protease 8',8152);
        this.modelMap.set('Retinoic acid receptor RXR-alpha',8172);
        this.modelMap.set('Sphingosine 1-phosphate receptor 1',8174);
        this.modelMap.set('Sphingosine 1-phosphate receptor 3',8177);
        this.modelMap.set('Sodium-dependent noradrenaline transporter',8206);
        this.modelMap.set('Sodium-dependent proline transporter',8209);
        this.modelMap.set('High affinity choline transporter 1',8251);
        this.modelMap.set('Sodium- and chloride-dependent glycine transporter 1',8301);
        this.modelMap.set('Sodium/glucose cotransporter 2',8304);
        this.modelMap.set('Multidrug and toxin extrusion protein 2',8346);
        this.modelMap.set('Sodium-dependent dopamine transporter',8358);
        this.modelMap.set('Sodium channel protein type 5 subunit alpha',8363);
        this.modelMap.set('Sodium channel protein type 10 subunit alpha',8364);
        this.modelMap.set('Sodium channel protein type 3 subunit alpha',8369);
        this.modelMap.set('Multidrug and toxin extrusion protein 1',8391);
        this.modelMap.set('3-oxo-5-alpha-steroid 4-dehydrogenase 2',8394);
        this.modelMap.set('Sodium-dependent serotonin transporter',8449);
        this.modelMap.set('Sodium channel protein type 9 subunit alpha',8459);
        this.modelMap.set('Sodium/glucose cotransporter 1',8472);
        this.modelMap.set('Sodium- and chloride-dependent glycine transporter 2',8478);
        this.modelMap.set('Sodium channel protein type 4 subunit alpha',8479);
        this.modelMap.set('Sodium channel protein type 1 subunit alpha',8481);
        this.modelMap.set('Long-chain fatty acid transport protein 4',8503);
        this.modelMap.set('Sodium- and chloride-dependent GABA transporter 1',8507);
        this.modelMap.set('Sentrin-specific protease 7',8522);
        this.modelMap.set('Serine/threonine-protein kinase TBK1',8543);
        this.modelMap.set('Trace amine-associated receptor 1',8566);
        this.modelMap.set('UDP-glucuronosyltransferase 2B7',8616);
        this.modelMap.set('Alpha-synuclein',8620);
        this.modelMap.set('Isoleucine--tRNA ligase, cytoplasmic',8637);
        this.modelMap.set('Leucine--tRNA ligase, cytoplasmic',8674);
        this.modelMap.set('TGF-beta-activated kinase 1 and MAP3K7-binding protein 1',8723);
        this.modelMap.set('Urokinase plasminogen activator surface receptor',8729);
        this.modelMap.set('Telomeric repeat-binding factor 2-interacting protein 1',8788);
        this.modelMap.set('Transcription factor p65',8818);
        this.modelMap.set('Protein-glutamine gamma-glutamyltransferase K',8855);
        this.modelMap.set('Tissue factor',8881);
        this.modelMap.set('TGF-beta receptor type-1',8932);
        this.modelMap.set('TGF-beta receptor type-2',8933);
        this.modelMap.set('Protein-glutamine gamma-glutamyltransferase E',8979);
        this.modelMap.set('Troponin I, cardiac muscle',9010);
        this.modelMap.set('Transcription intermediary factor 1-alpha',9019);
        this.modelMap.set('Toll-like receptor 4',9029);
        this.modelMap.set('Thromboxane-A synthase',9034);
        this.modelMap.set('DNA topoisomerase 1',9048);
        this.modelMap.set('Protein tyrosine phosphatase type IVA 1',9049);
        this.modelMap.set('Transient receptor potential cation channel subfamily A member 1',9052);
        this.modelMap.set('DNA topoisomerase 2-alpha',9079);
        this.modelMap.set('Angiopoietin-1 receptor',9089);
        this.modelMap.set('Thyroid hormone receptor alpha',9133);
        this.modelMap.set('Transitional endoplasmic reticulum ATPase',9141);
        this.modelMap.set('Telomerase reverse transcriptase',9147);
        this.modelMap.set('Toll-like receptor 9',9223);
        this.modelMap.set('Troponin T, cardiac muscle',9243);
        this.modelMap.set('Solute carrier organic anion transporter family member 2B1',9286);
        this.modelMap.set('Sterol O-acyltransferase 1',9289);
        this.modelMap.set('Sentrin-specific protease 6',9348);
        this.modelMap.set('Histone-lysine N-methyltransferase SETD7',9351);
        this.modelMap.set('Sex hormone-binding globulin',9390);
        this.modelMap.set('Mothers against decapentaplegic homolog 3',9416);
        this.modelMap.set('Prolyl endopeptidase FAP',9479);
        this.modelMap.set('NAD-dependent protein deacetylase sirtuin-1',9506);
        this.modelMap.set('Sphingosine-1-phosphate lyase 1',9519);
        this.modelMap.set('Sigma non-opioid intracellular receptor 1',9552);
        this.modelMap.set('Trypsin-1',9592);
        this.modelMap.set('Dual specificity protein kinase TTK',9629);
        this.modelMap.set('Tyrosyl-DNA phosphodiesterase 2',9664);
        this.modelMap.set('Tumor necrosis factor receptor superfamily member 1A',9670);
        this.modelMap.set('Transthyretin',9675);
        this.modelMap.set('Transient receptor potential cation channel subfamily V member 4',9706);
        this.modelMap.set('Serine/threonine-protein kinase PLK4',9803);
        this.modelMap.set('Protein phosphatase methylesterase 1',9818);
        this.modelMap.set('Serine/threonine-protein kinase pim-1',9835);
        this.modelMap.set('Prokineticin receptor 1',9840);
        this.modelMap.set('Phosphatidylinositol 4,5-bisphosphate 3-kinase catalytic subunit gamma isoform',9843);
        this.modelMap.set('Phenylethanolamine N-methyltransferase',9866);
        this.modelMap.set('Phospholipase A-2-activating protein',9882);
        this.modelMap.set('Dual 3\',5\'-cyclic-AMP and -GMP phosphodiesterase 11A',9938);
        this.modelMap.set('Prostaglandin E2 receptor EP2 subtype',9939);
        this.modelMap.set('Gamma-secretase subunit PEN-2',9942);
        this.modelMap.set('Peptidyl-prolyl cis-trans isomerase B',9968);
        this.modelMap.set('Progesterone receptor',9980);
        this.modelMap.set('Phosphomannomutase 2',9987);
        this.modelMap.set('Serine/threonine-protein kinase PLK3',10027);
        this.modelMap.set('Peptidyl-prolyl cis-trans isomerase NIMA-interacting 1',10067);
        this.modelMap.set('Serine/threonine-protein kinase N1',10082);
        this.modelMap.set('Platelet-derived growth factor receptor alpha',10102);
        this.modelMap.set('Serine/threonine-protein kinase PLK2',10120);
        this.modelMap.set('Phosphatidylinositol 4,5-bisphosphate 3-kinase catalytic subunit alpha isoform',10136);
        this.modelMap.set('1-acyl-sn-glycerol-3-phosphate acyltransferase beta',10138);
        this.modelMap.set('Plasminogen',10142);
        this.modelMap.set('Serine/threonine-protein kinase pim-2',10154);
        this.modelMap.set('Phosphatidylinositol 4,5-bisphosphate 3-kinase catalytic subunit beta isoform',10162);
        this.modelMap.set('Phosphatidylinositol 4,5-bisphosphate 3-kinase catalytic subunit delta isoform',10164);
        this.modelMap.set('Serine/threonine-protein kinase PLK1',10167);
        this.modelMap.set('Retinol-binding protein 4',10169);
        this.modelMap.set('Serine/threonine-protein kinase pim-3',10184);
        this.modelMap.set('Phosphoglycerate kinase 1',10196);
        this.modelMap.set('Histone lysine demethylase PHF8',10219);
        this.modelMap.set('Renin',10304);
        this.modelMap.set('Prostaglandin D2 receptor',10392);
        this.modelMap.set('High affinity cAMP-specific 3\',5\'-cyclic phosphodiesterase 7A',10399);
        this.modelMap.set('cAMP and cAMP-inhibited cGMP 3\',5\'-cyclic phosphodiesterase 10A',10401);
        this.modelMap.set('cAMP-specific 3\',5\'-cyclic phosphodiesterase 4D',10402);
        this.modelMap.set('Core-binding factor subunit beta',10403);
        this.modelMap.set('Putative inactive group IIC secretory phospholipase A2',10426);
        this.modelMap.set('Pituitary adenylate cyclase-activating polypeptide type I receptor',10430);
        this.modelMap.set('Protein-arginine deiminase type-4',10431);
        this.modelMap.set('High affinity cGMP-specific 3\',5\'-cyclic phosphodiesterase 9A',10459);
        this.modelMap.set('cGMP-inhibited 3\',5\'-cyclic phosphodiesterase A',10461);
        this.modelMap.set('cAMP-specific 3\',5\'-cyclic phosphodiesterase 4C',10463);
        this.modelMap.set('Prostaglandin E2 receptor EP4 subtype',10470);
        this.modelMap.set('Platelet-derived growth factor receptor beta',10475);
        this.modelMap.set('Prostaglandin G/H synthase 1',10479);
        this.modelMap.set('Proteinase-activated receptor 1',10488);
        this.modelMap.set('Poly [ADP-ribose] polymerase 10',10493);
        this.modelMap.set('Lysosomal Pro-X carboxypeptidase',10504);
        this.modelMap.set('High affinity cAMP-specific and IBMX-insensitive 3\',5\'-cyclic phosphodiesterase 8B',10506);
        this.modelMap.set('Poly [ADP-ribose] polymerase 3',10508);
        this.modelMap.set('Prostaglandin D2 receptor 2',10514);
        this.modelMap.set('cGMP-specific 3\',5\'-cyclic phosphodiesterase',10515);
        this.modelMap.set('[Pyruvate dehydrogenase (acetyl-transferring)] kinase isozyme 1, mitochondrial',10519);
        this.modelMap.set('Prostaglandin E2 receptor EP1 subtype',10528);
        this.modelMap.set('cGMP-inhibited 3\',5\'-cyclic phosphodiesterase B',10538);
        this.modelMap.set('cAMP-specific 3\',5\'-cyclic phosphodiesterase 4A',10540);
        this.modelMap.set('cAMP-specific 3\',5\'-cyclic phosphodiesterase 4B',10541);
        this.modelMap.set('Prostaglandin F2-alpha receptor',10566);
        this.modelMap.set('Poly(ADP-ribose) glycohydrolase',10573);
        this.modelMap.set('Protein phosphatase 1B',10701);
        this.modelMap.set('GTPase HRas',10722);
        this.modelMap.set('Prostacyclin receptor',10750);
        this.modelMap.set('Placenta growth factor',10752);
        this.modelMap.set('Proteinase-activated receptor 2',10775);
        this.modelMap.set('Poly [ADP-ribose] polymerase 1',10776);
        this.modelMap.set('Poly [ADP-ribose] polymerase 2',10778);
        this.modelMap.set('Phosphoenolpyruvate carboxykinase, cytosolic [GTP]',10787);
        this.modelMap.set('Calcium/calmodulin-dependent 3\',5\'-cyclic nucleotide phosphodiesterase 1C',10796);
        this.modelMap.set('Advanced glycosylation end product-specific receptor',10806);
        this.modelMap.set('Prostaglandin E synthase 2',10807);
        this.modelMap.set('Prostaglandin G/H synthase 2',10808);
        this.modelMap.set('Myeloperoxidase',10818);
        this.modelMap.set('Perforin-1',10819);
        this.modelMap.set('[Pyruvate dehydrogenase (acetyl-transferring)] kinase isozyme 2, mitochondrial',10844);
        this.modelMap.set('Geranylgeranyl transferase type-1 subunit beta',10847);
        this.modelMap.set('Phosphoethanolamine/phosphocholine phosphatase',10871);
        this.modelMap.set('Phosphatidylinositol 4-kinase alpha',10874);
        this.modelMap.set('Phosphatidylinositol 4-kinase beta',10876);
        this.modelMap.set('Prostaglandin E2 receptor EP3 subtype',10893);
        this.modelMap.set('15-hydroxyprostaglandin dehydrogenase [NAD(+)]',10903);
        this.modelMap.set('cGMP-dependent 3\',5\'-cyclic phosphodiesterase',10933);
        this.modelMap.set('Neprilysin',10956);
        this.modelMap.set('Neuromedin-K receptor',10961);
        this.modelMap.set('Calcium/calmodulin-dependent 3\',5\'-cyclic nucleotide phosphodiesterase 1B',10981);
        this.modelMap.set('Putative hydrolase RBBP9',11005);
        this.modelMap.set('Receptor-interacting serine/threonine-protein kinase 1',11095);
        this.modelMap.set('Ribonucleoside-diphosphate reductase subunit M2',11173);
        this.modelMap.set('Lysine-specific histone demethylase 1A',11197);
        this.modelMap.set('Lysine-specific demethylase 4B',11200);
        this.modelMap.set('Lysine-specific demethylase 4C',11201);
        this.modelMap.set('Lysine-specific demethylase 5A',11202);
        this.modelMap.set('Lysine-specific demethylase 5C',11203);
        this.modelMap.set('Lysine-specific demethylase 6B',11206);
        this.modelMap.set('Protein kinase C zeta type',11237);
        this.modelMap.set('Ribosomal protein S6 kinase beta-1',11257);
        this.modelMap.set('MAP kinase-interacting serine/threonine-protein kinase 2',11266);
        this.modelMap.set('Interstitial collagenase',11270);
        this.modelMap.set('Matrilysin',11280);
        this.modelMap.set('Kallikrein-7',11309);
        this.modelMap.set('Kynurenine 3-monooxygenase',11310);
        this.modelMap.set('Protein kinase C delta type',11327);
        this.modelMap.set('Ribosomal protein S6 kinase alpha-1',11329);
        this.modelMap.set('Ribosomal protein S6 kinase alpha-2',11331);
        this.modelMap.set('Tyrosine-protein kinase SYK',11333);
        this.modelMap.set('Protein kinase C beta type',11340);
        this.modelMap.set('Protein kinase C epsilon type',11350);
        this.modelMap.set('Mitogen-activated protein kinase 10',11363);
        this.modelMap.set('Mitogen-activated protein kinase 12',11364);
        this.modelMap.set('Mitogen-activated protein kinase 8',11373);
        this.modelMap.set('MAP kinase-interacting serine/threonine-protein kinase 1',11379);
        this.modelMap.set('Collagenase 3',11389);
        this.modelMap.set('Matrix metalloproteinase-14',11390);
        this.modelMap.set('L-lactate dehydrogenase B chain',11398);
        this.modelMap.set('Matrix metalloproteinase-9',11424);
        this.modelMap.set('Protein kinase C eta type',11439);
        this.modelMap.set('Ribosomal protein S6 kinase alpha-5',11452);
        this.modelMap.set('Kinesin-like protein KIF20A',11478);
        this.modelMap.set('Kinesin-like protein KIF11',11481);
        this.modelMap.set('Kinesin-like protein KIFC1',11484);
        this.modelMap.set('Kallikrein-1',11504);
        this.modelMap.set('Kallikrein-5',11508);
        this.modelMap.set('Serine/threonine-protein kinase D1',11512);
        this.modelMap.set('Plasma kallikrein',11527);
        this.modelMap.set('Protein kinase C iota type',11536);
        this.modelMap.set('Membrane-associated guanylate kinase, WW and PDZ domain-containing protein 3',11545);
        this.modelMap.set('Methionine aminopeptidase 2',11550);
        this.modelMap.set('2-acylglycerol O-acyltransferase 2',11609);
        this.modelMap.set('Mannose-6-phosphate isomerase',11645);
        this.modelMap.set('M-phase inducer phosphatase 1',11646);
        this.modelMap.set('Alpha-1,6-mannosyl-glycoprotein 2-beta-N-acetylglucosaminyltransferase',11679);
        this.modelMap.set('Monoglyceride lipase',11680);
        this.modelMap.set('Macrophage migration inhibitory factor',11686);
        this.modelMap.set('Macrophage metalloelastase',11691);
        this.modelMap.set('Macrophage-expressed gene 1 protein',11730);
        this.modelMap.set('Melanocortin receptor 5',11740);
        this.modelMap.set('Mineralocorticoid receptor',11754);
        this.modelMap.set('Methylated-DNA--protein-cysteine methyltransferase',11762);
        this.modelMap.set('Induced myeloid leukemia cell differentiation protein Mcl-1',11802);
        this.modelMap.set('Stromelysin-2',11835);
        this.modelMap.set('MAP kinase-activated protein kinase 2',11837);
        this.modelMap.set('Arachidonate 12-lipoxygenase, 12S-type',11862);
        this.modelMap.set('Arachidonate 5-lipoxygenase',11868);
        this.modelMap.set('72 kDa type IV collagenase',11889);
        this.modelMap.set('Lipoprotein lipase',11902);
        this.modelMap.set('Hormone-sensitive lipase',11962);
        this.modelMap.set('Lethal(3)malignant brain tumor-like protein 1',11989);
        this.modelMap.set('LIM domain kinase 1',12002);
        this.modelMap.set('Lethal(3)malignant brain tumor-like protein 3',12007);
        this.modelMap.set('Hepatic triacylglycerol lipase',12015);
        this.modelMap.set('Leukotriene A-4 hydrolase',12019);
        this.modelMap.set('Lysosomal alpha-glucosidase',12096);
        this.modelMap.set('Mitogen-activated protein kinase kinase kinase 7',12109);
        this.modelMap.set('Tyrosine-protein kinase Lck',12122);
        this.modelMap.set('Legumain',12130);
        this.modelMap.set('Lysophosphatidic acid receptor 3',12170);
        this.modelMap.set('LIM domain kinase 2',12201);
        this.modelMap.set('Lysophosphatidic acid receptor 1',12205);
        this.modelMap.set('L-selectin',12227);
        this.modelMap.set('Matrix metalloproteinase-16',12271);
        this.modelMap.set('Melanin-concentrating hormone receptor 2',12328);
        this.modelMap.set('Serine/threonine-protein kinase Nek2',12329);
        this.modelMap.set('Maltase-glucoamylase, intestinal',12341);
        this.modelMap.set('Lactoylglutathione lyase',12357);
        this.modelMap.set('Endothelial lipase',12359);
        this.modelMap.set('Arachidonate 15-lipoxygenase',12370);
        this.modelMap.set('Lysophosphatidic acid receptor 2',12372);
        this.modelMap.set('Leukotriene B4 receptor 1',12406);
        this.modelMap.set('E-selectin',12413);
        this.modelMap.set('Mitogen-activated protein kinase kinase kinase 14',12441);
        this.modelMap.set('Lysosomal alpha-mannosidase',12484);
        this.modelMap.set('Leucine-rich repeat serine/threonine-protein kinase 2',12500);
        this.modelMap.set('P-selectin',12509);
        this.modelMap.set('Mucosa-associated lymphoid tissue lymphoma translocation protein 1',12517);
        this.modelMap.set('Mitogen-activated protein kinase kinase kinase 8',12519);
        this.modelMap.set('Melanocortin receptor 4',12524);
        this.modelMap.set('Myelin-associated glycoprotein',12573);
        this.modelMap.set('Mitogen-activated protein kinase kinase kinase kinase 4',12581);
        this.modelMap.set('MAP kinase-activated protein kinase 5',12584);
        this.modelMap.set('Dual specificity mitogen-activated protein kinase kinase 7',12649);
        this.modelMap.set('Canalicular multispecific organic anion transporter 1',12677);
        this.modelMap.set('Microtubule-associated protein 2',12703);
        this.modelMap.set('Integrin beta-6',12742);
        this.modelMap.set('Tyrosine-protein kinase JAK1',12748);
        this.modelMap.set('Serine/threonine-protein kinase MRCK alpha',12778);
        this.modelMap.set('Multidrug resistance-associated protein 4',12793);
        this.modelMap.set('Tyrosine-protein kinase Lyn',12831);
        this.modelMap.set('Mitogen-activated protein kinase kinase kinase 5',12841);
        this.modelMap.set('Melanocortin receptor 3',12845);
        this.modelMap.set('Nuclear receptor subfamily 0 group B member 1',12854);
        this.modelMap.set('Oxysterols receptor LXR-beta',12858);
        this.modelMap.set('Oxysterols receptor LXR-alpha',12859);
        this.modelMap.set('Bile acid receptor',12860);
        this.modelMap.set('Nuclear receptor subfamily 1 group I member 2',12861);
        this.modelMap.set('Nuclear receptor subfamily 1 group I member 3',12862);
        this.modelMap.set('Nuclear receptor subfamily 4 group A member 1',12865);
        this.modelMap.set('Caspase-1',12961);
        this.modelMap.set('Cyclin-A1',12982);
        this.modelMap.set('G2/mitotic-specific cyclin-B3',12983);
        this.modelMap.set('Complement C1r subcomponent',12989);
        this.modelMap.set('Cathepsin B',13007);
        this.modelMap.set('Bromodomain-containing protein 9',13016);
        this.modelMap.set('Cytochrome P450 11B2, mitochondrial',13018);
        this.modelMap.set('Voltage-dependent T-type calcium channel subunit alpha-1G',13062);
        this.modelMap.set('Carbonic anhydrase 1',13070);
        this.modelMap.set('Voltage-dependent L-type calcium channel subunit alpha-1C',13073);
        this.modelMap.set('Cathepsin D',13083);
        this.modelMap.set('Extracellular calcium-sensing receptor',13097);
        this.modelMap.set('Voltage-dependent N-type calcium channel subunit alpha-1B',13130);
        this.modelMap.set('Carbonic anhydrase 2',13132);
        this.modelMap.set('Calcitonin gene-related peptide type 1 receptor',13134);
        this.modelMap.set('Caspase-3',13141);
        this.modelMap.set('Caspase-6',13142);
        this.modelMap.set('Cytochrome P450 11B1, mitochondrial',13147);
        this.modelMap.set('C5a anaphylatoxin chemotactic receptor 1',13159);
        this.modelMap.set('Histone-arginine methyltransferase CARM1',13183);
        this.modelMap.set('Carbonic anhydrase 12',13220);
        this.modelMap.set('Calpain-1 catalytic subunit',13228);
        this.modelMap.set('Gamma-butyrobetaine dioxygenase',13310);
        this.modelMap.set('Bone morphogenetic protein 1',13316);
        this.modelMap.set('Bromodomain testis-specific protein',13329);
        this.modelMap.set('Serine/threonine-protein kinase B-raf',13343);
        this.modelMap.set('Bromodomain-containing protein 3',13346);
        this.modelMap.set('Peregrin',13370);
        this.modelMap.set('Tyrosine-protein kinase BTK',13383);
        this.modelMap.set('C3a anaphylatoxin chemotactic receptor',13388);
        this.modelMap.set('Carbonic anhydrase 14',13404);
        this.modelMap.set('Carbonic anhydrase 9',13405);
        this.modelMap.set('Bromodomain-containing protein 2',13416);
        this.modelMap.set('Voltage-dependent calcium channel subunit alpha-2/delta-1',13449);
        this.modelMap.set('Protein arginine N-methyltransferase 1',13463);
        this.modelMap.set('B2 bradykinin receptor',13501);
        this.modelMap.set('Baculoviral IAP repeat-containing protein 2',13503);
        this.modelMap.set('Cytoplasmic tyrosine-protein kinase BMX',13506);
        this.modelMap.set('Branched-chain-amino-acid aminotransferase, cytosolic',13526);
        this.modelMap.set('Breakpoint cluster region protein',13529);
        this.modelMap.set('Aromatase',13532);
        this.modelMap.set('Beta-galactosidase',13541);
        this.modelMap.set('Cytochrome P450 1A1',13543);
        this.modelMap.set('Bromodomain adjacent to zinc finger domain protein 2A',13567);
        this.modelMap.set('Bcl2-associated agonist of cell death',13588);
        this.modelMap.set('Branched-chain-amino-acid aminotransferase, mitochondrial',13590);
        this.modelMap.set('Apoptosis regulator Bcl-2',13600);
        this.modelMap.set('Beta-glucuronidase',13609);
        this.modelMap.set('Steroid 17-alpha-hydroxylase/17,20 lyase',13628);
        this.modelMap.set('B1 bradykinin receptor',13632);
        this.modelMap.set('Bloom syndrome protein',13637);
        this.modelMap.set('Beta-secretase 1',13655);
        this.modelMap.set('Beta-secretase 2',13656);
        this.modelMap.set('Bromodomain adjacent to zinc finger domain protein 2B',13662);
        this.modelMap.set('Cysteinyl leukotriene receptor 2',13695);
        this.modelMap.set('Serine/threonine-protein kinase ATR',13712);
        this.modelMap.set('A disintegrin and metalloproteinase with thrombospondin motifs 4',13721);
        this.modelMap.set('Aurora kinase A',13732);
        this.modelMap.set('Bcl-2-like protein 1',13753);
        this.modelMap.set('Bcl-2-related protein A1',13761);
        this.modelMap.set('Arginase-2, mitochondrial',13799);
        this.modelMap.set('ATPase family AAA domain-containing protein 2',13825);
        this.modelMap.set('Cysteinyl leukotriene receptor 1',13836);
        this.modelMap.set('A disintegrin and metalloproteinase with thrombospondin motifs 5',13857);
        this.modelMap.set('Chymase',13912);
        this.modelMap.set('Aurora kinase B',13990);
        this.modelMap.set('Cyclin-dependent kinase 6',14044);
        this.modelMap.set('Catechol O-methyltransferase',14141);
        this.modelMap.set('D(3) dopamine receptor',14143);
        this.modelMap.set('Urotensin-2 receptor',14148);
        this.modelMap.set('Vasopressin V1b receptor',14150);
        this.modelMap.set('Vasopressin V2 receptor',14151);
        this.modelMap.set('Urokinase-type plasminogen activator',14164);
        this.modelMap.set('Cystine/glutamate transporter',14255);
        this.modelMap.set('E3 ubiquitin-protein ligase XIAP',14306);
        this.modelMap.set('X-box-binding protein 1',14331);
        this.modelMap.set('Transient receptor potential cation channel subfamily M member 8',14412);
        this.modelMap.set('Wee1-like protein kinase',14440);
        this.modelMap.set('WD repeat-containing protein 5',14532);
        this.modelMap.set('Xanthine dehydrogenase/oxidase',14627);
        this.modelMap.set('Tyrosinase',14636);
        this.modelMap.set('Tyrosine-protein kinase ZAP-70',15001);
        this.modelMap.set('Protein Wnt-3a',15116);
        this.modelMap.set('Vascular cell adhesion protein 1',15125);
        this.modelMap.set('Vascular endothelial growth factor A',15134);
        this.modelMap.set('Vascular endothelial growth factor receptor 1',15139);
        this.modelMap.set('Vascular endothelial growth factor receptor 2',15140);
        this.modelMap.set('Tyrosyl-DNA phosphodiesterase 1',15186);
        this.modelMap.set('Ubiquitin-conjugating enzyme E2 N',15194);
        this.modelMap.set('Vesicular acetylcholine transporter',15212);
        this.modelMap.set('5-hydroxytryptamine receptor 1B',15254);
        this.modelMap.set('Neuronal acetylcholine receptor subunit alpha-7',15267);
        this.modelMap.set('Beta-2 adrenergic receptor',15277);
        this.modelMap.set('Disintegrin and metalloproteinase domain-containing protein 17',15280);
        this.modelMap.set('ATP-binding cassette sub-family G member 2',15285);
        this.modelMap.set('Activated CDC42 kinase 1',15304);
        this.modelMap.set('Neuronal acetylcholine receptor subunit alpha-3',15305);
        this.modelMap.set('Muscarinic acetylcholine receptor M5',15312);
        this.modelMap.set('Muscarinic acetylcholine receptor M3',15325);
        this.modelMap.set('Acetyl-CoA carboxylase 2',15342);
        this.modelMap.set('Acetylcholine receptor subunit alpha',15345);
        this.modelMap.set('DNA dC->dU-editing enzyme APOBEC-3G',15351);
        this.modelMap.set('Muscarinic acetylcholine receptor M4',15353);
        this.modelMap.set('Alpha-2B adrenergic receptor',15360);
        this.modelMap.set('5-hydroxytryptamine receptor 4',15369);
        this.modelMap.set('Muscarinic acetylcholine receptor M2',15379);
        this.modelMap.set('Neuronal acetylcholine receptor subunit beta-2',15382);
        this.modelMap.set('Neuronal acetylcholine receptor subunit beta-4',15384);
        this.modelMap.set('Alpha-2C adrenergic receptor',15387);
        this.modelMap.set('Alcohol dehydrogenase class-3',15392);
        this.modelMap.set('Apelin receptor',15445);
        this.modelMap.set('Gamma-secretase subunit APH-1A',15446);
        this.modelMap.set('Cytosol aminopeptidase',15468);
        this.modelMap.set('Amiloride-sensitive amine oxidase [copper-containing]',15473);
        this.modelMap.set('DNA-(apurinic or apyrimidinic site) lyase',15486);
        this.modelMap.set('Gamma-secretase subunit APH-1B',15506);
        this.modelMap.set('Membrane primary amine oxidase',15513);
        this.modelMap.set('5-hydroxytryptamine receptor 2A',15543);
        this.modelMap.set('Adenosine receptor A2a',15544);
        this.modelMap.set('Adenosine receptor A2b',15560);
        this.modelMap.set('Neuronal acetylcholine receptor subunit alpha-4',15568);
        this.modelMap.set('Angiotensin-converting enzyme',15580);
        this.modelMap.set('Acetylcholinesterase',15595);
        this.modelMap.set('Tyrosine-protein kinase ABL1',15608);
        this.modelMap.set('5-hydroxytryptamine receptor 1E',15624);
        this.modelMap.set('5-hydroxytryptamine receptor 7',15625);
        this.modelMap.set('Bile salt export pump',15644);
        this.modelMap.set('Acetyl-CoA carboxylase 1',15676);
        this.modelMap.set('Alpha-1B adrenergic receptor',15686);
        this.modelMap.set('Adenylate cyclase type 5',15692);
        this.modelMap.set('Atypical chemokine receptor 3',15709);
        this.modelMap.set('Disintegrin and metalloproteinase domain-containing protein 10',15714);
        this.modelMap.set('Beta-3 adrenergic receptor',15731);
        this.modelMap.set('RAC-gamma serine/threonine-protein kinase',15751);
        this.modelMap.set('Acrosin',15777);
        this.modelMap.set('Activin receptor type-1B',15778);
        this.modelMap.set('Alpha-galactosidase A',15785);
        this.modelMap.set('Acyl-CoA desaturase',15805);
        this.modelMap.set('Muscarinic acetylcholine receptor M1',15806);
        this.modelMap.set('Aldo-keto reductase family 1 member C2',15823);
        this.modelMap.set('Alpha-2A adrenergic receptor',15848);
        this.modelMap.set('Disintegrin and metalloproteinase domain-containing protein 9',15850);
        this.modelMap.set('Aldo-keto reductase family 1 member C3',15853);
        this.modelMap.set('Aldehyde dehydrogenase, dimeric NADP-preferring',15868);
        this.modelMap.set('Arachidonate 5-lipoxygenase-activating protein',15870);
        this.modelMap.set('Beta-1 adrenergic receptor',15871);
        this.modelMap.set('Aldo-keto reductase family 1 member B10',15880);
        this.modelMap.set('ALK tyrosine kinase receptor',15882);
        this.modelMap.set('Alpha-1D adrenergic receptor',15894);
        this.modelMap.set('Type-1 angiotensin II receptor',15898);
        this.modelMap.set('Adenosine kinase',15907);
        this.modelMap.set('Alpha-ketoglutarate-dependent dioxygenase alkB homolog 3',15926);
        this.modelMap.set('Alpha-amylase 1',15930);
        this.modelMap.set('Alpha-1A adrenergic receptor',15934);
        this.modelMap.set('Aldo-keto reductase family 1 member C1',15942);
        this.modelMap.set('Type-2 angiotensin II receptor',15952);
        this.modelMap.set('Peptidyl-glycine alpha-amidating monooxygenase',15960);
        this.modelMap.set('RAC-beta serine/threonine-protein kinase',15962);
        this.modelMap.set('Androgen receptor',15965);
        this.modelMap.set('Amine oxidase [flavin-containing] B',15970);
        this.modelMap.set('Aminopeptidase N',15977);
        this.modelMap.set('RAC-alpha serine/threonine-protein kinase',15991);
        this.modelMap.set('Retina-specific copper amine oxidase',16034);
        this.modelMap.set('Amine oxidase [flavin-containing] A',16037);
        this.modelMap.set('Aldose reductase',16041);
        this.modelMap.set('Alcohol dehydrogenase [NADP(+)]',16058);
        this.modelMap.set('Retinal dehydrogenase 1',16071);
        this.modelMap.set('Protein arginine N-methyltransferase 6',16081);
        this.modelMap.set('Aldehyde dehydrogenase, mitochondrial',16102);
        this.modelMap.set('14-3-3 protein gamma',16107);
        this.modelMap.set('5-hydroxytryptamine receptor 1D',16115);
        this.modelMap.set('ATP-binding cassette sub-family C member 8',16117);
        this.modelMap.set('DNA dC->dU-editing enzyme APOBEC-3A',16157);
        this.modelMap.set('5-hydroxytryptamine receptor 2C',16165);
        this.modelMap.set('5\'-nucleotidase',16168);
        this.modelMap.set('Adenosine receptor A1',16170);
        this.modelMap.set('HLA class II histocompatibility antigen, DRB1-1 beta chain',16174);
        this.modelMap.set('HLA class I histocompatibility antigen, A-3 alpha chain',16191);
        this.modelMap.set('5-hydroxytryptamine receptor 1A',16194);
        this.modelMap.set('Adenosine receptor A3',16195);
        this.modelMap.set('5-hydroxytryptamine receptor 3A',16197);
        this.modelMap.set('5-hydroxytryptamine receptor 6',16199);
        this.modelMap.set('5-hydroxytryptamine receptor 2B',16218);
        this.modelMap.set('Serine/threonine-protein kinase Chk1',16239);
        this.modelMap.set('Serine/threonine-protein kinase Chk2',16241);
        this.modelMap.set('Choline kinase alpha',16242);
        this.modelMap.set('Steryl-sulfatase',16301);
        this.modelMap.set('Sucrase-isomaltase, intestinal',16346);
        this.modelMap.set('Thromboxane A2 receptor',16434);
        this.modelMap.set('Tyrosine-protein kinase receptor UFO',16468);
        this.modelMap.set('Tryptophan 2,3-dioxygenase',16503);
        this.modelMap.set('Sortilin',16527);
        this.modelMap.set('Serine/threonine-protein kinase TNNI3K',16542);
        this.modelMap.set('Tankyrase-2',16545);
        this.modelMap.set('Protein-glutamine gamma-glutamyltransferase 2',16625);
        this.modelMap.set('Thyroid hormone receptor beta',16629);
        this.modelMap.set('Xaa-Pro aminopeptidase 2',16633);
        this.modelMap.set('Toll-like receptor 7',16655);
        this.modelMap.set('Prothrombin',16701);
        this.modelMap.set('Microtubule-associated protein tau',16745);
        this.modelMap.set('Acidic mammalian chitinase',16806);
        this.modelMap.set('Cysteine protease ATG4B',16845);
        this.modelMap.set('Serine-protein kinase ATM',16861);
        this.modelMap.set('Dual specificity protein kinase CLK3',16915);
        this.modelMap.set('Histone chaperone ASF1A',16948);
        this.modelMap.set('Acid-sensing ion channel 3',16952);
        this.modelMap.set('Choline O-acetyltransferase',16990);
        this.modelMap.set('Dual specificity protein kinase CLK1',17027);
        this.modelMap.set('Dual specificity protein kinase CLK2',17028);
        this.modelMap.set('Dual specificity protein kinase CLK4',17029);
        this.modelMap.set('Protein arginine N-methyltransferase 3',17039);
        this.modelMap.set('CDGSH iron-sulfur domain-containing protein 1',17054);
        this.modelMap.set('Cyclic AMP-dependent transcription factor ATF-1',17111);
        this.modelMap.set('Arginase-1',17275);
        this.modelMap.set('Arylamine N-acetyltransferase 1',17308);
        this.modelMap.set('Acid ceramidase',17310);
        this.modelMap.set('Apoptotic protease-activating factor 1',17329);
        this.modelMap.set('Beta-adrenergic receptor kinase 1',17334);
        this.modelMap.set('Cholinesterase',17341);
        this.modelMap.set('G-protein coupled bile acid receptor 1',17439);
        this.modelMap.set('Metabotropic glutamate receptor 1',17452);
        this.modelMap.set('Endothelin-1 receptor',17480);
        this.modelMap.set('Eukaryotic elongation factor 2 kinase',17491);
        this.modelMap.set('G protein-activated inward rectifier potassium channel 1',17536);
        this.modelMap.set('Thymidine kinase 2, mitochondrial',17565);
        this.modelMap.set('Potassium/sodium hyperpolarization-activated cyclic nucleotide-gated channel 1',17567);
        this.modelMap.set('Histone deacetylase 10',17570);
        this.modelMap.set('Histone deacetylase 8',17572);
        this.modelMap.set('Histone deacetylase 5',17582);
        this.modelMap.set('Glucosylceramidase',17591);
        this.modelMap.set('Glutathione S-transferase A2',17594);
        this.modelMap.set('Glutamate receptor ionotropic, kainate 1',17630);
        this.modelMap.set('G protein-coupled receptor kinase 6',17633);
        this.modelMap.set('Glycogen synthase kinase-3 beta',17638);
        this.modelMap.set('Potassium channel subfamily K member 2',17644);
        this.modelMap.set('Potassium channel subfamily K member 3',17645);
        this.modelMap.set('Intermediate conductance calcium-activated potassium channel protein 4',17647);
        this.modelMap.set('Glutamate receptor ionotropic, kainate 2',17706);
        this.modelMap.set('Metabotropic glutamate receptor 2',17709);
        this.modelMap.set('Metabotropic glutamate receptor 4',17710);
        this.modelMap.set('Metabotropic glutamate receptor 5',17711);
        this.modelMap.set('Glycogen synthase kinase-3 alpha',17728);
        this.modelMap.set('Solute carrier family 2, facilitated glucose transporter member 1',17752);
        this.modelMap.set('Solute carrier family 2, facilitated glucose transporter member 2',17755);
        this.modelMap.set('Small conductance calcium-activated potassium channel protein 3',17758);
        this.modelMap.set('Tyrosine-protein kinase HCK',17768);
        this.modelMap.set('Mast/stem cell growth factor receptor Kit',17769);
        this.modelMap.set('Potassium/sodium hyperpolarization-activated cyclic nucleotide-gated channel 4',17770);
        this.modelMap.set('Histone deacetylase 3',17781);
        this.modelMap.set('Huntingtin',17782);
        this.modelMap.set('Krueppel-like factor 5',17783);
        this.modelMap.set('Galanin receptor type 3',17788);
        this.modelMap.set('Zinc finger protein GLI2',17793);
        this.modelMap.set('Glucagon receptor',17795);
        this.modelMap.set('Glutamate carboxypeptidase 2',17805);
        this.modelMap.set('Glucose-6-phosphate 1-dehydrogenase',17818);
        this.modelMap.set('Glycine receptor subunit alpha-1',17827);
        this.modelMap.set('Indolethylamine N-methyltransferase',17871);
        this.modelMap.set('Zinc finger protein GLI1',17873);
        this.modelMap.set('Inner centromere protein',17898);
        this.modelMap.set('Galanin receptor type 2',17946);
        this.modelMap.set('Glutamate receptor 1',17952);
        this.modelMap.set('G protein-coupled receptor kinase 5',17957);
        this.modelMap.set('Metabotropic glutamate receptor 3',17959);
        this.modelMap.set('Metabotropic glutamate receptor 6',17960);
        this.modelMap.set('Glutathione reductase, mitochondrial',17968);
        this.modelMap.set('Potassium voltage-gated channel subfamily H member 2',17974);
        this.modelMap.set('ATP-sensitive inward rectifier potassium channel 1',17976);
        this.modelMap.set('G protein-activated inward rectifier potassium channel 4',17977);
        this.modelMap.set('Potassium channel subfamily K member 9',17979);
        this.modelMap.set('Inosine-5\'-monophosphate dehydrogenase 2',18029);
        this.modelMap.set('Gonadotropin-releasing hormone receptor',18039);
        this.modelMap.set('Insulin receptor',18061);
        this.modelMap.set('Inosine-5\'-monophosphate dehydrogenase 1',18080);
        this.modelMap.set('Intercellular adhesion molecule 1',18131);
        this.modelMap.set('Glucagon-like peptide 1 receptor',18144);
        this.modelMap.set('Glutaminase kidney isoform, mitochondrial',18157);
        this.modelMap.set('Isocitrate dehydrogenase [NADP] cytoplasmic',18190);
        this.modelMap.set('Phospholipase A2',18203);
        this.modelMap.set('Group 10 secretory phospholipase A2',18206);
        this.modelMap.set('Serine/threonine-protein kinase PAK 4',18213);
        this.modelMap.set('Pantothenate kinase 3',18222);
        this.modelMap.set('Serine/threonine-protein kinase PAK 1',18246);
        this.modelMap.set('Bifunctional purine biosynthesis protein PURH',18255);
        this.modelMap.set('NUAK family SNF1-like kinase 1',18261);
        this.modelMap.set('Platelet-activating factor receptor',18290);
        this.modelMap.set('Orexin receptor type 2',18304);
        this.modelMap.set('P2Y purinoceptor 12',18310);
        this.modelMap.set('P2X purinoceptor 3',18311);
        this.modelMap.set('P2X purinoceptor 4',18312);
        this.modelMap.set('P2X purinoceptor 7',18314);
        this.modelMap.set('P2Y purinoceptor 1',18315);
        this.modelMap.set('Cellular tumor antigen p53',18320);
        this.modelMap.set('Phospholipase A2, membrane associated',18322);
        this.modelMap.set('Phosphatidylinositol 3-kinase regulatory subunit alpha',18332);
        this.modelMap.set('Calcium-dependent phospholipase A2',18335);
        this.modelMap.set('Presenilin-2',18381);
        this.modelMap.set('Delta-type opioid receptor',18385);
        this.modelMap.set('Kappa-type opioid receptor',18386);
        this.modelMap.set('Nociceptin receptor',18387);
        this.modelMap.set('Oxoeicosanoid receptor 1',18498);
        this.modelMap.set('D-amino-acid oxidase',18500);
        this.modelMap.set('P2X purinoceptor 2',18514);
        this.modelMap.set('Transmembrane prolyl 4-hydroxylase',18517);
        this.modelMap.set('Platelet-activating factor acetylhydrolase IB subunit beta',18519);
        this.modelMap.set('Mu-type opioid receptor',18529);
        this.modelMap.set('Oxytocin receptor',18664);
        this.modelMap.set('Platelet-activating factor acetylhydrolase',18684);
        this.modelMap.set('Neuromedin-B receptor',18790);
        this.modelMap.set('Glutamate receptor ionotropic, NMDA 1',18793);
        this.modelMap.set('Nucleotide-binding oligomerization domain-containing protein 2',18794);
        this.modelMap.set('Glycylpeptide N-tetradecanoyltransferase 1',18796);
        this.modelMap.set('Nitric oxide synthase, inducible',18803);
        this.modelMap.set('BDNF/NT-3 growth factors receptor',18822);
        this.modelMap.set('Low molecular weight phosphotyrosine protein phosphatase',18840);
        this.modelMap.set('Prostatic acid phosphatase',18843);
        this.modelMap.set('Peroxisome proliferator-activated receptor alpha',18844);
        this.modelMap.set('Peroxisome proliferator-activated receptor delta',18845);
        this.modelMap.set('Prolyl endopeptidase',18846);
        this.modelMap.set('Neuropeptide Y receptor type 5',18864);
        this.modelMap.set('Ribosyldihydronicotinamide dehydrogenase [quinone]',18865);
        this.modelMap.set('Ileal sodium/bile acid cotransporter',18890);
        this.modelMap.set('Sodium/bile acid cotransporter',18893);
        this.modelMap.set('High affinity nerve growth factor receptor',18902);
        this.modelMap.set('Intestinal-type alkaline phosphatase',18906);
        this.modelMap.set('Alkaline phosphatase, tissue-nonspecific isozyme',18907);
        this.modelMap.set('Glutamate receptor ionotropic, NMDA 2A',18916);
        this.modelMap.set('Glutamate receptor ionotropic, NMDA 2B',18917);
        this.modelMap.set('Presenilin-1',18996);
        this.modelMap.set('Sialidase-4',19007);
        this.modelMap.set('Peroxisome proliferator-activated receptor gamma',19023);
        this.modelMap.set('Lysosomal protective protein',19028);
        this.modelMap.set('Nicastrin',19040);
        this.modelMap.set('NADPH oxidase 1',19048);
        this.modelMap.set('Serine/threonine-protein phosphatase PP1-alpha catalytic subunit',19080);
        this.modelMap.set('NF-kappa-B essential modulator',19086);
        this.modelMap.set('NADPH oxidase 4',19091);
        this.modelMap.set('Peptidyl-prolyl cis-trans isomerase A',19100);
        this.modelMap.set('Substance-P receptor',19114);
        this.modelMap.set('Substance-K receptor',19115);
        this.modelMap.set('NAD(P)H dehydrogenase [quinone] 1',19130);
        this.modelMap.set('Neuropeptide S receptor',19173);
        this.modelMap.set('Neuropeptide Y receptor type 1',19175);
        this.modelMap.set('Casein kinase I isoform alpha',19201);
        this.modelMap.set('Calcium/calmodulin-dependent protein kinase type II subunit alpha',19210);
        this.modelMap.set('Calcium/calmodulin-dependent protein kinase type II subunit delta',19211);
        this.modelMap.set('ATP-sensitive inward rectifier potassium channel 11',19228);
        this.modelMap.set('Potassium voltage-gated channel subfamily A member 3',19231);
        this.modelMap.set('Interleukin-8',19264);
        this.modelMap.set('Potassium voltage-gated channel subfamily A member 5',19284);
        this.modelMap.set('Calcium-activated potassium channel subunit alpha-1',19285);
        this.modelMap.set('Indoleamine 2,3-dioxygenase 1',19312);
        this.modelMap.set('Integrin beta-1',19336);
        this.modelMap.set('Integrin alpha-5',19338);
        this.modelMap.set('Integrin alpha-L',19339);
        this.modelMap.set('Integrin alpha-V',19340);
        this.modelMap.set('Eukaryotic translation initiation factor 4H',19351);
        this.modelMap.set('Tyrosine-protein kinase JAK2',19360);
        this.modelMap.set('cAMP-dependent protein kinase catalytic subunit alpha',19373);
        this.modelMap.set('Lysine-specific demethylase 2A',19375);
        this.modelMap.set('Lysine-specific demethylase 3A',19376);
        this.modelMap.set('Lysine-specific demethylase 4A',19377);
        this.modelMap.set('Lysine-specific demethylase 4E',19379);
        this.modelMap.set('Lysine-specific demethylase 5B',19380);
        this.modelMap.set('Kinesin-1 heavy chain',19383);
        this.modelMap.set('Menin',19410);
        this.modelMap.set('Ketohexokinase',19419);
        this.modelMap.set('Kallikrein-14',19437);
        this.modelMap.set('Protein kinase C gamma type',19439);
        this.modelMap.set('Protein kinase C alpha type',19440);
        this.modelMap.set('Ribosomal protein S6 kinase beta-2',19459);
        this.modelMap.set('Mitogen-activated protein kinase 1',19468);
        this.modelMap.set('Mitogen-activated protein kinase 3',19469);
        this.modelMap.set('Mitogen-activated protein kinase 9',19481);
        this.modelMap.set('Mitogen-activated protein kinase 11',19482);
        this.modelMap.set('Mitogen-activated protein kinase 14',19485);
        this.modelMap.set('Stromelysin-1',19493);
        this.modelMap.set('Neutrophil collagenase',19494);
        this.modelMap.set('L-lactate dehydrogenase A chain',19523);
        this.modelMap.set('Protein kinase C theta type',19535);
        this.modelMap.set('Ribosomal protein S6 kinase alpha-3',19547);
        this.modelMap.set('Leucyl-cystinyl aminopeptidase',19556);
        this.modelMap.set('Melanocyte-stimulating hormone receptor',19603);
        this.modelMap.set('Phosphatidylinositol 4-phosphate 3-kinase C2 domain-containing subunit beta',19628);
        this.modelMap.set('Mitogen-activated protein kinase kinase kinase 9',19635);
        this.modelMap.set('Methionine aminopeptidase 1',19637);
        this.modelMap.set('Malate dehydrogenase, mitochondrial',19645);
        this.modelMap.set('Photoreceptor-specific nuclear receptor',19657);
        this.modelMap.set('Natural resistance-associated macrophage protein 2',19664);
        this.modelMap.set('Multidrug resistance-associated protein 1',19684);
        this.modelMap.set('Melanin-concentrating hormone receptor 1',19770);
        this.modelMap.set('Monocarboxylate transporter 4',19792);
        this.modelMap.set('Dual specificity mitogen-activated protein kinase kinase 1',19797);
        this.modelMap.set('M-phase inducer phosphatase 2',19825);
        this.modelMap.set('M-phase inducer phosphatase 3',19827);
        this.modelMap.set('Cation-independent mannose-6-phosphate receptor',19834);
        this.modelMap.set('P2X purinoceptor 1',19855);
        this.modelMap.set('Melatonin receptor type 1A',19858);
        this.modelMap.set('Sodium/calcium exchanger 1',19877);
        this.modelMap.set('Nitric oxide synthase, brain',19957);
        this.modelMap.set('Neuropeptide Y receptor type 2',19969);
        this.modelMap.set('Nuclear receptor coactivator 1',19993);
        this.modelMap.set('Nuclear receptor coactivator 3',19995);
        this.modelMap.set('NACHT, LRR and PYD domains-containing protein 3',20029);
        this.modelMap.set('Neuropeptides B/W receptor type 1',20045);
        this.modelMap.set('Purine nucleoside phosphorylase',20063);
        this.modelMap.set('Nucleotide-binding oligomerization domain-containing protein 1',20079);
        this.modelMap.set('Nuclear factor NF-kappa-B p105 subunit',20088);
        this.modelMap.set('Nitric oxide synthase, endothelial',20130);
        this.modelMap.set('Neutral cholesterol ester hydrolase 1',20134);
        this.modelMap.set('N-acylethanolamine-hydrolyzing acid amidase',20204);
        this.modelMap.set('Nicotinamide phosphoribosyltransferase',20208);
        this.modelMap.set('Nuclear receptor corepressor 2',20222);
        this.modelMap.set('Serine/threonine-protein kinase mTOR',20357);
        this.modelMap.set('Myosin light chain kinase, smooth muscle',20387);
        this.modelMap.set('3-phosphoinositide-dependent protein kinase 1',20392);
        this.modelMap.set('Melatonin receptor type 1B',20408);
    }
}
